// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.1
// source: software/services.proto

package software

import (
	common "github.com/richardlt/matrix/sdk-go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectRequest_Type int32

const (
	ConnectRequest_PING     ConnectRequest_Type = 0
	ConnectRequest_SOFTWARE ConnectRequest_Type = 1
	ConnectRequest_LAYER    ConnectRequest_Type = 2
	ConnectRequest_DRIVER   ConnectRequest_Type = 3
)

// Enum value maps for ConnectRequest_Type.
var (
	ConnectRequest_Type_name = map[int32]string{
		0: "PING",
		1: "SOFTWARE",
		2: "LAYER",
		3: "DRIVER",
	}
	ConnectRequest_Type_value = map[string]int32{
		"PING":     0,
		"SOFTWARE": 1,
		"LAYER":    2,
		"DRIVER":   3,
	}
)

func (x ConnectRequest_Type) Enum() *ConnectRequest_Type {
	p := new(ConnectRequest_Type)
	*p = x
	return p
}

func (x ConnectRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_software_services_proto_enumTypes[0].Descriptor()
}

func (ConnectRequest_Type) Type() protoreflect.EnumType {
	return &file_software_services_proto_enumTypes[0]
}

func (x ConnectRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectRequest_Type.Descriptor instead.
func (ConnectRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{0, 0}
}

type ConnectRequest_SoftwareData_Action int32

const (
	ConnectRequest_SoftwareData_REGISTER   ConnectRequest_SoftwareData_Action = 0
	ConnectRequest_SoftwareData_READY      ConnectRequest_SoftwareData_Action = 1
	ConnectRequest_SoftwareData_PRINT      ConnectRequest_SoftwareData_Action = 2
	ConnectRequest_SoftwareData_SET_CONFIG ConnectRequest_SoftwareData_Action = 3
)

// Enum value maps for ConnectRequest_SoftwareData_Action.
var (
	ConnectRequest_SoftwareData_Action_name = map[int32]string{
		0: "REGISTER",
		1: "READY",
		2: "PRINT",
		3: "SET_CONFIG",
	}
	ConnectRequest_SoftwareData_Action_value = map[string]int32{
		"REGISTER":   0,
		"READY":      1,
		"PRINT":      2,
		"SET_CONFIG": 3,
	}
)

func (x ConnectRequest_SoftwareData_Action) Enum() *ConnectRequest_SoftwareData_Action {
	p := new(ConnectRequest_SoftwareData_Action)
	*p = x
	return p
}

func (x ConnectRequest_SoftwareData_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectRequest_SoftwareData_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_software_services_proto_enumTypes[1].Descriptor()
}

func (ConnectRequest_SoftwareData_Action) Type() protoreflect.EnumType {
	return &file_software_services_proto_enumTypes[1]
}

func (x ConnectRequest_SoftwareData_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectRequest_SoftwareData_Action.Descriptor instead.
func (ConnectRequest_SoftwareData_Action) EnumDescriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{0, 0, 0}
}

type ConnectRequest_LayerData_Action int32

const (
	ConnectRequest_LayerData_CLEAN          ConnectRequest_LayerData_Action = 0
	ConnectRequest_LayerData_REMOVE         ConnectRequest_LayerData_Action = 1
	ConnectRequest_LayerData_SET_WITH_COORD ConnectRequest_LayerData_Action = 2
)

// Enum value maps for ConnectRequest_LayerData_Action.
var (
	ConnectRequest_LayerData_Action_name = map[int32]string{
		0: "CLEAN",
		1: "REMOVE",
		2: "SET_WITH_COORD",
	}
	ConnectRequest_LayerData_Action_value = map[string]int32{
		"CLEAN":          0,
		"REMOVE":         1,
		"SET_WITH_COORD": 2,
	}
)

func (x ConnectRequest_LayerData_Action) Enum() *ConnectRequest_LayerData_Action {
	p := new(ConnectRequest_LayerData_Action)
	*p = x
	return p
}

func (x ConnectRequest_LayerData_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectRequest_LayerData_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_software_services_proto_enumTypes[2].Descriptor()
}

func (ConnectRequest_LayerData_Action) Type() protoreflect.EnumType {
	return &file_software_services_proto_enumTypes[2]
}

func (x ConnectRequest_LayerData_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectRequest_LayerData_Action.Descriptor instead.
func (ConnectRequest_LayerData_Action) EnumDescriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{0, 1, 0}
}

type ConnectRequest_DriverData_Action int32

const (
	ConnectRequest_DriverData_RENDER ConnectRequest_DriverData_Action = 0
	ConnectRequest_DriverData_STOP   ConnectRequest_DriverData_Action = 1
)

// Enum value maps for ConnectRequest_DriverData_Action.
var (
	ConnectRequest_DriverData_Action_name = map[int32]string{
		0: "RENDER",
		1: "STOP",
	}
	ConnectRequest_DriverData_Action_value = map[string]int32{
		"RENDER": 0,
		"STOP":   1,
	}
)

func (x ConnectRequest_DriverData_Action) Enum() *ConnectRequest_DriverData_Action {
	p := new(ConnectRequest_DriverData_Action)
	*p = x
	return p
}

func (x ConnectRequest_DriverData_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectRequest_DriverData_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_software_services_proto_enumTypes[3].Descriptor()
}

func (ConnectRequest_DriverData_Action) Type() protoreflect.EnumType {
	return &file_software_services_proto_enumTypes[3]
}

func (x ConnectRequest_DriverData_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectRequest_DriverData_Action.Descriptor instead.
func (ConnectRequest_DriverData_Action) EnumDescriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{0, 2, 0}
}

type ConnectResponse_Type int32

const (
	ConnectResponse_PING     ConnectResponse_Type = 0
	ConnectResponse_SOFTWARE ConnectResponse_Type = 1
	ConnectResponse_DRIVER   ConnectResponse_Type = 2
)

// Enum value maps for ConnectResponse_Type.
var (
	ConnectResponse_Type_name = map[int32]string{
		0: "PING",
		1: "SOFTWARE",
		2: "DRIVER",
	}
	ConnectResponse_Type_value = map[string]int32{
		"PING":     0,
		"SOFTWARE": 1,
		"DRIVER":   2,
	}
)

func (x ConnectResponse_Type) Enum() *ConnectResponse_Type {
	p := new(ConnectResponse_Type)
	*p = x
	return p
}

func (x ConnectResponse_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectResponse_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_software_services_proto_enumTypes[4].Descriptor()
}

func (ConnectResponse_Type) Type() protoreflect.EnumType {
	return &file_software_services_proto_enumTypes[4]
}

func (x ConnectResponse_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectResponse_Type.Descriptor instead.
func (ConnectResponse_Type) EnumDescriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{1, 0}
}

type ConnectResponse_SoftwareData_Action int32

const (
	ConnectResponse_SoftwareData_INIT           ConnectResponse_SoftwareData_Action = 0
	ConnectResponse_SoftwareData_START          ConnectResponse_SoftwareData_Action = 1
	ConnectResponse_SoftwareData_CLOSE          ConnectResponse_SoftwareData_Action = 2
	ConnectResponse_SoftwareData_PLAYER_COMMAND ConnectResponse_SoftwareData_Action = 3
)

// Enum value maps for ConnectResponse_SoftwareData_Action.
var (
	ConnectResponse_SoftwareData_Action_name = map[int32]string{
		0: "INIT",
		1: "START",
		2: "CLOSE",
		3: "PLAYER_COMMAND",
	}
	ConnectResponse_SoftwareData_Action_value = map[string]int32{
		"INIT":           0,
		"START":          1,
		"CLOSE":          2,
		"PLAYER_COMMAND": 3,
	}
)

func (x ConnectResponse_SoftwareData_Action) Enum() *ConnectResponse_SoftwareData_Action {
	p := new(ConnectResponse_SoftwareData_Action)
	*p = x
	return p
}

func (x ConnectResponse_SoftwareData_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectResponse_SoftwareData_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_software_services_proto_enumTypes[5].Descriptor()
}

func (ConnectResponse_SoftwareData_Action) Type() protoreflect.EnumType {
	return &file_software_services_proto_enumTypes[5]
}

func (x ConnectResponse_SoftwareData_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectResponse_SoftwareData_Action.Descriptor instead.
func (ConnectResponse_SoftwareData_Action) EnumDescriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{1, 0, 0}
}

type ConnectResponse_DriverData_Action int32

const (
	ConnectResponse_DriverData_END  ConnectResponse_DriverData_Action = 0
	ConnectResponse_DriverData_STEP ConnectResponse_DriverData_Action = 1
)

// Enum value maps for ConnectResponse_DriverData_Action.
var (
	ConnectResponse_DriverData_Action_name = map[int32]string{
		0: "END",
		1: "STEP",
	}
	ConnectResponse_DriverData_Action_value = map[string]int32{
		"END":  0,
		"STEP": 1,
	}
)

func (x ConnectResponse_DriverData_Action) Enum() *ConnectResponse_DriverData_Action {
	p := new(ConnectResponse_DriverData_Action)
	*p = x
	return p
}

func (x ConnectResponse_DriverData_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectResponse_DriverData_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_software_services_proto_enumTypes[6].Descriptor()
}

func (ConnectResponse_DriverData_Action) Type() protoreflect.EnumType {
	return &file_software_services_proto_enumTypes[6]
}

func (x ConnectResponse_DriverData_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectResponse_DriverData_Action.Descriptor instead.
func (ConnectResponse_DriverData_Action) EnumDescriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{1, 1, 0}
}

type CreateRequest_Type int32

const (
	CreateRequest_LAYER  CreateRequest_Type = 0
	CreateRequest_DRIVER CreateRequest_Type = 1
)

// Enum value maps for CreateRequest_Type.
var (
	CreateRequest_Type_name = map[int32]string{
		0: "LAYER",
		1: "DRIVER",
	}
	CreateRequest_Type_value = map[string]int32{
		"LAYER":  0,
		"DRIVER": 1,
	}
)

func (x CreateRequest_Type) Enum() *CreateRequest_Type {
	p := new(CreateRequest_Type)
	*p = x
	return p
}

func (x CreateRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_software_services_proto_enumTypes[7].Descriptor()
}

func (CreateRequest_Type) Type() protoreflect.EnumType {
	return &file_software_services_proto_enumTypes[7]
}

func (x CreateRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateRequest_Type.Descriptor instead.
func (CreateRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{2, 0}
}

type CreateRequest_DriverData_Type int32

const (
	CreateRequest_DriverData_RANDOM   CreateRequest_DriverData_Type = 0
	CreateRequest_DriverData_CARACTER CreateRequest_DriverData_Type = 1
	CreateRequest_DriverData_TEXT     CreateRequest_DriverData_Type = 2
	CreateRequest_DriverData_IMAGE    CreateRequest_DriverData_Type = 3
)

// Enum value maps for CreateRequest_DriverData_Type.
var (
	CreateRequest_DriverData_Type_name = map[int32]string{
		0: "RANDOM",
		1: "CARACTER",
		2: "TEXT",
		3: "IMAGE",
	}
	CreateRequest_DriverData_Type_value = map[string]int32{
		"RANDOM":   0,
		"CARACTER": 1,
		"TEXT":     2,
		"IMAGE":    3,
	}
)

func (x CreateRequest_DriverData_Type) Enum() *CreateRequest_DriverData_Type {
	p := new(CreateRequest_DriverData_Type)
	*p = x
	return p
}

func (x CreateRequest_DriverData_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateRequest_DriverData_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_software_services_proto_enumTypes[8].Descriptor()
}

func (CreateRequest_DriverData_Type) Type() protoreflect.EnumType {
	return &file_software_services_proto_enumTypes[8]
}

func (x CreateRequest_DriverData_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateRequest_DriverData_Type.Descriptor instead.
func (CreateRequest_DriverData_Type) EnumDescriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{2, 1, 0}
}

type CreateResponse_Type int32

const (
	CreateResponse_LAYER  CreateResponse_Type = 0
	CreateResponse_DRIVER CreateResponse_Type = 1
)

// Enum value maps for CreateResponse_Type.
var (
	CreateResponse_Type_name = map[int32]string{
		0: "LAYER",
		1: "DRIVER",
	}
	CreateResponse_Type_value = map[string]int32{
		"LAYER":  0,
		"DRIVER": 1,
	}
)

func (x CreateResponse_Type) Enum() *CreateResponse_Type {
	p := new(CreateResponse_Type)
	*p = x
	return p
}

func (x CreateResponse_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateResponse_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_software_services_proto_enumTypes[9].Descriptor()
}

func (CreateResponse_Type) Type() protoreflect.EnumType {
	return &file_software_services_proto_enumTypes[9]
}

func (x CreateResponse_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateResponse_Type.Descriptor instead.
func (CreateResponse_Type) EnumDescriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{3, 0}
}

type LoadRequest_Type int32

const (
	LoadRequest_IMAGE LoadRequest_Type = 0
	LoadRequest_COLOR LoadRequest_Type = 1
	LoadRequest_FONT  LoadRequest_Type = 2
)

// Enum value maps for LoadRequest_Type.
var (
	LoadRequest_Type_name = map[int32]string{
		0: "IMAGE",
		1: "COLOR",
		2: "FONT",
	}
	LoadRequest_Type_value = map[string]int32{
		"IMAGE": 0,
		"COLOR": 1,
		"FONT":  2,
	}
)

func (x LoadRequest_Type) Enum() *LoadRequest_Type {
	p := new(LoadRequest_Type)
	*p = x
	return p
}

func (x LoadRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoadRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_software_services_proto_enumTypes[10].Descriptor()
}

func (LoadRequest_Type) Type() protoreflect.EnumType {
	return &file_software_services_proto_enumTypes[10]
}

func (x LoadRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoadRequest_Type.Descriptor instead.
func (LoadRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{4, 0}
}

type LoadResponse_Type int32

const (
	LoadResponse_IMAGE LoadResponse_Type = 0
	LoadResponse_COLOR LoadResponse_Type = 1
	LoadResponse_FONT  LoadResponse_Type = 2
)

// Enum value maps for LoadResponse_Type.
var (
	LoadResponse_Type_name = map[int32]string{
		0: "IMAGE",
		1: "COLOR",
		2: "FONT",
	}
	LoadResponse_Type_value = map[string]int32{
		"IMAGE": 0,
		"COLOR": 1,
		"FONT":  2,
	}
)

func (x LoadResponse_Type) Enum() *LoadResponse_Type {
	p := new(LoadResponse_Type)
	*p = x
	return p
}

func (x LoadResponse_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoadResponse_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_software_services_proto_enumTypes[11].Descriptor()
}

func (LoadResponse_Type) Type() protoreflect.EnumType {
	return &file_software_services_proto_enumTypes[11]
}

func (x LoadResponse_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoadResponse_Type.Descriptor instead.
func (LoadResponse_Type) EnumDescriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{5, 0}
}

type ConnectRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Type          ConnectRequest_Type          `protobuf:"varint,1,opt,name=type,proto3,enum=software.ConnectRequest_Type" json:"type,omitempty"`
	SoftwareData  *ConnectRequest_SoftwareData `protobuf:"bytes,2,opt,name=softwareData,proto3" json:"softwareData,omitempty"`
	LayerData     *ConnectRequest_LayerData    `protobuf:"bytes,3,opt,name=layerData,proto3" json:"layerData,omitempty"`
	DriverData    *ConnectRequest_DriverData   `protobuf:"bytes,4,opt,name=driverData,proto3" json:"driverData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_software_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_software_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectRequest) GetType() ConnectRequest_Type {
	if x != nil {
		return x.Type
	}
	return ConnectRequest_PING
}

func (x *ConnectRequest) GetSoftwareData() *ConnectRequest_SoftwareData {
	if x != nil {
		return x.SoftwareData
	}
	return nil
}

func (x *ConnectRequest) GetLayerData() *ConnectRequest_LayerData {
	if x != nil {
		return x.LayerData
	}
	return nil
}

func (x *ConnectRequest) GetDriverData() *ConnectRequest_DriverData {
	if x != nil {
		return x.DriverData
	}
	return nil
}

type ConnectResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Type          ConnectResponse_Type          `protobuf:"varint,1,opt,name=type,proto3,enum=software.ConnectResponse_Type" json:"type,omitempty"`
	SoftwareData  *ConnectResponse_SoftwareData `protobuf:"bytes,2,opt,name=softwareData,proto3" json:"softwareData,omitempty"`
	DriverData    *ConnectResponse_DriverData   `protobuf:"bytes,3,opt,name=driverData,proto3" json:"driverData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_software_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_software_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectResponse) GetType() ConnectResponse_Type {
	if x != nil {
		return x.Type
	}
	return ConnectResponse_PING
}

func (x *ConnectResponse) GetSoftwareData() *ConnectResponse_SoftwareData {
	if x != nil {
		return x.SoftwareData
	}
	return nil
}

func (x *ConnectResponse) GetDriverData() *ConnectResponse_DriverData {
	if x != nil {
		return x.DriverData
	}
	return nil
}

type CreateRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Type          CreateRequest_Type        `protobuf:"varint,1,opt,name=type,proto3,enum=software.CreateRequest_Type" json:"type,omitempty"`
	LayerData     *CreateRequest_LayerData  `protobuf:"bytes,2,opt,name=layerData,proto3" json:"layerData,omitempty"`
	DriverData    *CreateRequest_DriverData `protobuf:"bytes,3,opt,name=driverData,proto3" json:"driverData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_software_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_software_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRequest) GetType() CreateRequest_Type {
	if x != nil {
		return x.Type
	}
	return CreateRequest_LAYER
}

func (x *CreateRequest) GetLayerData() *CreateRequest_LayerData {
	if x != nil {
		return x.LayerData
	}
	return nil
}

func (x *CreateRequest) GetDriverData() *CreateRequest_DriverData {
	if x != nil {
		return x.DriverData
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          CreateResponse_Type    `protobuf:"varint,1,opt,name=type,proto3,enum=software.CreateResponse_Type" json:"type,omitempty"`
	UUID          string                 `protobuf:"bytes,2,opt,name=UUID,proto3" json:"UUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_software_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_software_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{3}
}

func (x *CreateResponse) GetType() CreateResponse_Type {
	if x != nil {
		return x.Type
	}
	return CreateResponse_LAYER
}

func (x *CreateResponse) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

type LoadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          LoadRequest_Type       `protobuf:"varint,1,opt,name=type,proto3,enum=software.LoadRequest_Type" json:"type,omitempty"`
	ImageData     *LoadRequest_ImageData `protobuf:"bytes,2,opt,name=imageData,proto3" json:"imageData,omitempty"`
	ColorData     *LoadRequest_ColorData `protobuf:"bytes,3,opt,name=colorData,proto3" json:"colorData,omitempty"`
	FontData      *LoadRequest_FontData  `protobuf:"bytes,4,opt,name=fontData,proto3" json:"fontData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadRequest) Reset() {
	*x = LoadRequest{}
	mi := &file_software_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadRequest) ProtoMessage() {}

func (x *LoadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_software_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadRequest.ProtoReflect.Descriptor instead.
func (*LoadRequest) Descriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{4}
}

func (x *LoadRequest) GetType() LoadRequest_Type {
	if x != nil {
		return x.Type
	}
	return LoadRequest_IMAGE
}

func (x *LoadRequest) GetImageData() *LoadRequest_ImageData {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *LoadRequest) GetColorData() *LoadRequest_ColorData {
	if x != nil {
		return x.ColorData
	}
	return nil
}

func (x *LoadRequest) GetFontData() *LoadRequest_FontData {
	if x != nil {
		return x.FontData
	}
	return nil
}

type LoadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          LoadResponse_Type      `protobuf:"varint,1,opt,name=type,proto3,enum=software.LoadResponse_Type" json:"type,omitempty"`
	Image         *Image                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Color         *common.Color          `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Font          *Font                  `protobuf:"bytes,4,opt,name=font,proto3" json:"font,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadResponse) Reset() {
	*x = LoadResponse{}
	mi := &file_software_services_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadResponse) ProtoMessage() {}

func (x *LoadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_software_services_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadResponse.ProtoReflect.Descriptor instead.
func (*LoadResponse) Descriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{5}
}

func (x *LoadResponse) GetType() LoadResponse_Type {
	if x != nil {
		return x.Type
	}
	return LoadResponse_IMAGE
}

func (x *LoadResponse) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *LoadResponse) GetColor() *common.Color {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *LoadResponse) GetFont() *Font {
	if x != nil {
		return x.Font
	}
	return nil
}

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Height        uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Width         uint64                 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Colors        []*common.Color        `protobuf:"bytes,4,rep,name=colors,proto3" json:"colors,omitempty"`
	Mask          []uint64               `protobuf:"varint,5,rep,packed,name=mask,proto3" json:"mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_software_services_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_software_services_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{6}
}

func (x *Image) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Image) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Image) GetWidth() uint64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Image) GetColors() []*common.Color {
	if x != nil {
		return x.Colors
	}
	return nil
}

func (x *Image) GetMask() []uint64 {
	if x != nil {
		return x.Mask
	}
	return nil
}

type Theme struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Name          string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Colors        map[string]*common.Color `protobuf:"bytes,2,rep,name=colors,proto3" json:"colors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Theme) Reset() {
	*x = Theme{}
	mi := &file_software_services_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Theme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Theme) ProtoMessage() {}

func (x *Theme) ProtoReflect() protoreflect.Message {
	mi := &file_software_services_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Theme.ProtoReflect.Descriptor instead.
func (*Theme) Descriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{7}
}

func (x *Theme) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Theme) GetColors() map[string]*common.Color {
	if x != nil {
		return x.Colors
	}
	return nil
}

type Font struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Name          string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Height        uint64                    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Caracters     map[string]*Font_Caracter `protobuf:"bytes,3,rep,name=caracters,proto3" json:"caracters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Font) Reset() {
	*x = Font{}
	mi := &file_software_services_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Font) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Font) ProtoMessage() {}

func (x *Font) ProtoReflect() protoreflect.Message {
	mi := &file_software_services_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Font.ProtoReflect.Descriptor instead.
func (*Font) Descriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{8}
}

func (x *Font) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Font) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Font) GetCaracters() map[string]*Font_Caracter {
	if x != nil {
		return x.Caracters
	}
	return nil
}

type ConnectRequest_SoftwareData struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Action        ConnectRequest_SoftwareData_Action  `protobuf:"varint,1,opt,name=action,proto3,enum=software.ConnectRequest_SoftwareData_Action" json:"action,omitempty"`
	UUID          string                              `protobuf:"bytes,2,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Config        *ConnectRequest_SoftwareData_Config `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest_SoftwareData) Reset() {
	*x = ConnectRequest_SoftwareData{}
	mi := &file_software_services_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest_SoftwareData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest_SoftwareData) ProtoMessage() {}

func (x *ConnectRequest_SoftwareData) ProtoReflect() protoreflect.Message {
	mi := &file_software_services_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest_SoftwareData.ProtoReflect.Descriptor instead.
func (*ConnectRequest_SoftwareData) Descriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ConnectRequest_SoftwareData) GetAction() ConnectRequest_SoftwareData_Action {
	if x != nil {
		return x.Action
	}
	return ConnectRequest_SoftwareData_REGISTER
}

func (x *ConnectRequest_SoftwareData) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *ConnectRequest_SoftwareData) GetConfig() *ConnectRequest_SoftwareData_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type ConnectRequest_LayerData struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Action        ConnectRequest_LayerData_Action `protobuf:"varint,1,opt,name=action,proto3,enum=software.ConnectRequest_LayerData_Action" json:"action,omitempty"`
	UUID          string                          `protobuf:"bytes,2,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Coord         *common.Coord                   `protobuf:"bytes,3,opt,name=coord,proto3" json:"coord,omitempty"`
	Color         *common.Color                   `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest_LayerData) Reset() {
	*x = ConnectRequest_LayerData{}
	mi := &file_software_services_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest_LayerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest_LayerData) ProtoMessage() {}

func (x *ConnectRequest_LayerData) ProtoReflect() protoreflect.Message {
	mi := &file_software_services_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest_LayerData.ProtoReflect.Descriptor instead.
func (*ConnectRequest_LayerData) Descriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ConnectRequest_LayerData) GetAction() ConnectRequest_LayerData_Action {
	if x != nil {
		return x.Action
	}
	return ConnectRequest_LayerData_CLEAN
}

func (x *ConnectRequest_LayerData) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *ConnectRequest_LayerData) GetCoord() *common.Coord {
	if x != nil {
		return x.Coord
	}
	return nil
}

func (x *ConnectRequest_LayerData) GetColor() *common.Color {
	if x != nil {
		return x.Color
	}
	return nil
}

type ConnectRequest_DriverData struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Action        ConnectRequest_DriverData_Action `protobuf:"varint,1,opt,name=action,proto3,enum=software.ConnectRequest_DriverData_Action" json:"action,omitempty"`
	UUID          string                           `protobuf:"bytes,2,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Caracter      string                           `protobuf:"bytes,3,opt,name=caracter,proto3" json:"caracter,omitempty"`
	Color         *common.Color                    `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	Background    *common.Color                    `protobuf:"bytes,5,opt,name=background,proto3" json:"background,omitempty"`
	Coord         *common.Coord                    `protobuf:"bytes,6,opt,name=coord,proto3" json:"coord,omitempty"`
	Text          string                           `protobuf:"bytes,7,opt,name=text,proto3" json:"text,omitempty"`
	Image         *Image                           `protobuf:"bytes,8,opt,name=image,proto3" json:"image,omitempty"`
	Repeat        bool                             `protobuf:"varint,9,opt,name=repeat,proto3" json:"repeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest_DriverData) Reset() {
	*x = ConnectRequest_DriverData{}
	mi := &file_software_services_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest_DriverData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest_DriverData) ProtoMessage() {}

func (x *ConnectRequest_DriverData) ProtoReflect() protoreflect.Message {
	mi := &file_software_services_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest_DriverData.ProtoReflect.Descriptor instead.
func (*ConnectRequest_DriverData) Descriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ConnectRequest_DriverData) GetAction() ConnectRequest_DriverData_Action {
	if x != nil {
		return x.Action
	}
	return ConnectRequest_DriverData_RENDER
}

func (x *ConnectRequest_DriverData) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *ConnectRequest_DriverData) GetCaracter() string {
	if x != nil {
		return x.Caracter
	}
	return ""
}

func (x *ConnectRequest_DriverData) GetColor() *common.Color {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *ConnectRequest_DriverData) GetBackground() *common.Color {
	if x != nil {
		return x.Background
	}
	return nil
}

func (x *ConnectRequest_DriverData) GetCoord() *common.Coord {
	if x != nil {
		return x.Coord
	}
	return nil
}

func (x *ConnectRequest_DriverData) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ConnectRequest_DriverData) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ConnectRequest_DriverData) GetRepeat() bool {
	if x != nil {
		return x.Repeat
	}
	return false
}

type ConnectRequest_SoftwareData_Config struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Logo           *Image                 `protobuf:"bytes,1,opt,name=logo,proto3" json:"logo,omitempty"`
	MinPlayerCount uint64                 `protobuf:"varint,2,opt,name=minPlayerCount,proto3" json:"minPlayerCount,omitempty"`
	MaxPlayerCount uint64                 `protobuf:"varint,3,opt,name=maxPlayerCount,proto3" json:"maxPlayerCount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConnectRequest_SoftwareData_Config) Reset() {
	*x = ConnectRequest_SoftwareData_Config{}
	mi := &file_software_services_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest_SoftwareData_Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest_SoftwareData_Config) ProtoMessage() {}

func (x *ConnectRequest_SoftwareData_Config) ProtoReflect() protoreflect.Message {
	mi := &file_software_services_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest_SoftwareData_Config.ProtoReflect.Descriptor instead.
func (*ConnectRequest_SoftwareData_Config) Descriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *ConnectRequest_SoftwareData_Config) GetLogo() *Image {
	if x != nil {
		return x.Logo
	}
	return nil
}

func (x *ConnectRequest_SoftwareData_Config) GetMinPlayerCount() uint64 {
	if x != nil {
		return x.MinPlayerCount
	}
	return 0
}

func (x *ConnectRequest_SoftwareData_Config) GetMaxPlayerCount() uint64 {
	if x != nil {
		return x.MaxPlayerCount
	}
	return 0
}

type ConnectResponse_SoftwareData struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Action        ConnectResponse_SoftwareData_Action `protobuf:"varint,1,opt,name=action,proto3,enum=software.ConnectResponse_SoftwareData_Action" json:"action,omitempty"`
	UUID          string                              `protobuf:"bytes,2,opt,name=UUID,proto3" json:"UUID,omitempty"`
	PlayerCount   uint64                              `protobuf:"varint,3,opt,name=playerCount,proto3" json:"playerCount,omitempty"`
	Slot          uint64                              `protobuf:"varint,4,opt,name=slot,proto3" json:"slot,omitempty"`
	Command       common.Command                      `protobuf:"varint,5,opt,name=command,proto3,enum=common.Command" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse_SoftwareData) Reset() {
	*x = ConnectResponse_SoftwareData{}
	mi := &file_software_services_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse_SoftwareData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse_SoftwareData) ProtoMessage() {}

func (x *ConnectResponse_SoftwareData) ProtoReflect() protoreflect.Message {
	mi := &file_software_services_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse_SoftwareData.ProtoReflect.Descriptor instead.
func (*ConnectResponse_SoftwareData) Descriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ConnectResponse_SoftwareData) GetAction() ConnectResponse_SoftwareData_Action {
	if x != nil {
		return x.Action
	}
	return ConnectResponse_SoftwareData_INIT
}

func (x *ConnectResponse_SoftwareData) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *ConnectResponse_SoftwareData) GetPlayerCount() uint64 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

func (x *ConnectResponse_SoftwareData) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *ConnectResponse_SoftwareData) GetCommand() common.Command {
	if x != nil {
		return x.Command
	}
	return common.Command(0)
}

type ConnectResponse_DriverData struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Action        ConnectResponse_DriverData_Action `protobuf:"varint,1,opt,name=action,proto3,enum=software.ConnectResponse_DriverData_Action" json:"action,omitempty"`
	UUID          string                            `protobuf:"bytes,2,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Total         uint64                            `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Current       uint64                            `protobuf:"varint,4,opt,name=current,proto3" json:"current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse_DriverData) Reset() {
	*x = ConnectResponse_DriverData{}
	mi := &file_software_services_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse_DriverData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse_DriverData) ProtoMessage() {}

func (x *ConnectResponse_DriverData) ProtoReflect() protoreflect.Message {
	mi := &file_software_services_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse_DriverData.ProtoReflect.Descriptor instead.
func (*ConnectResponse_DriverData) Descriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ConnectResponse_DriverData) GetAction() ConnectResponse_DriverData_Action {
	if x != nil {
		return x.Action
	}
	return ConnectResponse_DriverData_END
}

func (x *ConnectResponse_DriverData) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *ConnectResponse_DriverData) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ConnectResponse_DriverData) GetCurrent() uint64 {
	if x != nil {
		return x.Current
	}
	return 0
}

type CreateRequest_LayerData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SoftwareUUID  string                 `protobuf:"bytes,1,opt,name=softwareUUID,proto3" json:"softwareUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest_LayerData) Reset() {
	*x = CreateRequest_LayerData{}
	mi := &file_software_services_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest_LayerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest_LayerData) ProtoMessage() {}

func (x *CreateRequest_LayerData) ProtoReflect() protoreflect.Message {
	mi := &file_software_services_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest_LayerData.ProtoReflect.Descriptor instead.
func (*CreateRequest_LayerData) Descriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{2, 0}
}

func (x *CreateRequest_LayerData) GetSoftwareUUID() string {
	if x != nil {
		return x.SoftwareUUID
	}
	return ""
}

type CreateRequest_DriverData struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Type          CreateRequest_DriverData_Type `protobuf:"varint,1,opt,name=type,proto3,enum=software.CreateRequest_DriverData_Type" json:"type,omitempty"`
	SoftwareUUID  string                        `protobuf:"bytes,2,opt,name=softwareUUID,proto3" json:"softwareUUID,omitempty"`
	LayerUUID     string                        `protobuf:"bytes,3,opt,name=layerUUID,proto3" json:"layerUUID,omitempty"`
	Font          *Font                         `protobuf:"bytes,4,opt,name=font,proto3" json:"font,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest_DriverData) Reset() {
	*x = CreateRequest_DriverData{}
	mi := &file_software_services_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest_DriverData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest_DriverData) ProtoMessage() {}

func (x *CreateRequest_DriverData) ProtoReflect() protoreflect.Message {
	mi := &file_software_services_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest_DriverData.ProtoReflect.Descriptor instead.
func (*CreateRequest_DriverData) Descriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{2, 1}
}

func (x *CreateRequest_DriverData) GetType() CreateRequest_DriverData_Type {
	if x != nil {
		return x.Type
	}
	return CreateRequest_DriverData_RANDOM
}

func (x *CreateRequest_DriverData) GetSoftwareUUID() string {
	if x != nil {
		return x.SoftwareUUID
	}
	return ""
}

func (x *CreateRequest_DriverData) GetLayerUUID() string {
	if x != nil {
		return x.LayerUUID
	}
	return ""
}

func (x *CreateRequest_DriverData) GetFont() *Font {
	if x != nil {
		return x.Font
	}
	return nil
}

type LoadRequest_ImageData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadRequest_ImageData) Reset() {
	*x = LoadRequest_ImageData{}
	mi := &file_software_services_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadRequest_ImageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadRequest_ImageData) ProtoMessage() {}

func (x *LoadRequest_ImageData) ProtoReflect() protoreflect.Message {
	mi := &file_software_services_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadRequest_ImageData.ProtoReflect.Descriptor instead.
func (*LoadRequest_ImageData) Descriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{4, 0}
}

func (x *LoadRequest_ImageData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LoadRequest_ColorData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ThemeName     string                 `protobuf:"bytes,2,opt,name=themeName,proto3" json:"themeName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadRequest_ColorData) Reset() {
	*x = LoadRequest_ColorData{}
	mi := &file_software_services_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadRequest_ColorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadRequest_ColorData) ProtoMessage() {}

func (x *LoadRequest_ColorData) ProtoReflect() protoreflect.Message {
	mi := &file_software_services_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadRequest_ColorData.ProtoReflect.Descriptor instead.
func (*LoadRequest_ColorData) Descriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{4, 1}
}

func (x *LoadRequest_ColorData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoadRequest_ColorData) GetThemeName() string {
	if x != nil {
		return x.ThemeName
	}
	return ""
}

type LoadRequest_FontData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadRequest_FontData) Reset() {
	*x = LoadRequest_FontData{}
	mi := &file_software_services_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadRequest_FontData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadRequest_FontData) ProtoMessage() {}

func (x *LoadRequest_FontData) ProtoReflect() protoreflect.Message {
	mi := &file_software_services_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadRequest_FontData.ProtoReflect.Descriptor instead.
func (*LoadRequest_FontData) Descriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{4, 2}
}

func (x *LoadRequest_FontData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Font_Caracter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         uint64                 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Mask          []uint64               `protobuf:"varint,2,rep,packed,name=mask,proto3" json:"mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Font_Caracter) Reset() {
	*x = Font_Caracter{}
	mi := &file_software_services_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Font_Caracter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Font_Caracter) ProtoMessage() {}

func (x *Font_Caracter) ProtoReflect() protoreflect.Message {
	mi := &file_software_services_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Font_Caracter.ProtoReflect.Descriptor instead.
func (*Font_Caracter) Descriptor() ([]byte, []int) {
	return file_software_services_proto_rawDescGZIP(), []int{8, 0}
}

func (x *Font_Caracter) GetWidth() uint64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Font_Caracter) GetMask() []uint64 {
	if x != nil {
		return x.Mask
	}
	return nil
}

var File_software_services_proto protoreflect.FileDescriptor

const file_software_services_proto_rawDesc = "" +
	"\n" +
	"\x17software/services.proto\x12\bsoftware\x1a\x12common/types.proto\"\x8d\n" +
	"\n" +
	"\x0eConnectRequest\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.software.ConnectRequest.TypeR\x04type\x12I\n" +
	"\fsoftwareData\x18\x02 \x01(\v2%.software.ConnectRequest.SoftwareDataR\fsoftwareData\x12@\n" +
	"\tlayerData\x18\x03 \x01(\v2\".software.ConnectRequest.LayerDataR\tlayerData\x12C\n" +
	"\n" +
	"driverData\x18\x04 \x01(\v2#.software.ConnectRequest.DriverDataR\n" +
	"driverData\x1a\xeb\x02\n" +
	"\fSoftwareData\x12D\n" +
	"\x06action\x18\x01 \x01(\x0e2,.software.ConnectRequest.SoftwareData.ActionR\x06action\x12\x12\n" +
	"\x04UUID\x18\x02 \x01(\tR\x04UUID\x12D\n" +
	"\x06config\x18\x03 \x01(\v2,.software.ConnectRequest.SoftwareData.ConfigR\x06config\x1a}\n" +
	"\x06Config\x12#\n" +
	"\x04logo\x18\x01 \x01(\v2\x0f.software.ImageR\x04logo\x12&\n" +
	"\x0eminPlayerCount\x18\x02 \x01(\x04R\x0eminPlayerCount\x12&\n" +
	"\x0emaxPlayerCount\x18\x03 \x01(\x04R\x0emaxPlayerCount\"<\n" +
	"\x06Action\x12\f\n" +
	"\bREGISTER\x10\x00\x12\t\n" +
	"\x05READY\x10\x01\x12\t\n" +
	"\x05PRINT\x10\x02\x12\x0e\n" +
	"\n" +
	"SET_CONFIG\x10\x03\x1a\xe1\x01\n" +
	"\tLayerData\x12A\n" +
	"\x06action\x18\x01 \x01(\x0e2).software.ConnectRequest.LayerData.ActionR\x06action\x12\x12\n" +
	"\x04UUID\x18\x02 \x01(\tR\x04UUID\x12#\n" +
	"\x05coord\x18\x03 \x01(\v2\r.common.CoordR\x05coord\x12#\n" +
	"\x05color\x18\x04 \x01(\v2\r.common.ColorR\x05color\"3\n" +
	"\x06Action\x12\t\n" +
	"\x05CLEAN\x10\x00\x12\n" +
	"\n" +
	"\x06REMOVE\x10\x01\x12\x12\n" +
	"\x0eSET_WITH_COORD\x10\x02\x1a\xec\x02\n" +
	"\n" +
	"DriverData\x12B\n" +
	"\x06action\x18\x01 \x01(\x0e2*.software.ConnectRequest.DriverData.ActionR\x06action\x12\x12\n" +
	"\x04UUID\x18\x02 \x01(\tR\x04UUID\x12\x1a\n" +
	"\bcaracter\x18\x03 \x01(\tR\bcaracter\x12#\n" +
	"\x05color\x18\x04 \x01(\v2\r.common.ColorR\x05color\x12-\n" +
	"\n" +
	"background\x18\x05 \x01(\v2\r.common.ColorR\n" +
	"background\x12#\n" +
	"\x05coord\x18\x06 \x01(\v2\r.common.CoordR\x05coord\x12\x12\n" +
	"\x04text\x18\a \x01(\tR\x04text\x12%\n" +
	"\x05image\x18\b \x01(\v2\x0f.software.ImageR\x05image\x12\x16\n" +
	"\x06repeat\x18\t \x01(\bR\x06repeat\"\x1e\n" +
	"\x06Action\x12\n" +
	"\n" +
	"\x06RENDER\x10\x00\x12\b\n" +
	"\x04STOP\x10\x01\"5\n" +
	"\x04Type\x12\b\n" +
	"\x04PING\x10\x00\x12\f\n" +
	"\bSOFTWARE\x10\x01\x12\t\n" +
	"\x05LAYER\x10\x02\x12\n" +
	"\n" +
	"\x06DRIVER\x10\x03\"\xc3\x05\n" +
	"\x0fConnectResponse\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.software.ConnectResponse.TypeR\x04type\x12J\n" +
	"\fsoftwareData\x18\x02 \x01(\v2&.software.ConnectResponse.SoftwareDataR\fsoftwareData\x12D\n" +
	"\n" +
	"driverData\x18\x03 \x01(\v2$.software.ConnectResponse.DriverDataR\n" +
	"driverData\x1a\x88\x02\n" +
	"\fSoftwareData\x12E\n" +
	"\x06action\x18\x01 \x01(\x0e2-.software.ConnectResponse.SoftwareData.ActionR\x06action\x12\x12\n" +
	"\x04UUID\x18\x02 \x01(\tR\x04UUID\x12 \n" +
	"\vplayerCount\x18\x03 \x01(\x04R\vplayerCount\x12\x12\n" +
	"\x04slot\x18\x04 \x01(\x04R\x04slot\x12)\n" +
	"\acommand\x18\x05 \x01(\x0e2\x0f.common.CommandR\acommand\"<\n" +
	"\x06Action\x12\b\n" +
	"\x04INIT\x10\x00\x12\t\n" +
	"\x05START\x10\x01\x12\t\n" +
	"\x05CLOSE\x10\x02\x12\x12\n" +
	"\x0ePLAYER_COMMAND\x10\x03\x1a\xb2\x01\n" +
	"\n" +
	"DriverData\x12C\n" +
	"\x06action\x18\x01 \x01(\x0e2+.software.ConnectResponse.DriverData.ActionR\x06action\x12\x12\n" +
	"\x04UUID\x18\x02 \x01(\tR\x04UUID\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x04R\x05total\x12\x18\n" +
	"\acurrent\x18\x04 \x01(\x04R\acurrent\"\x1b\n" +
	"\x06Action\x12\a\n" +
	"\x03END\x10\x00\x12\b\n" +
	"\x04STEP\x10\x01\"*\n" +
	"\x04Type\x12\b\n" +
	"\x04PING\x10\x00\x12\f\n" +
	"\bSOFTWARE\x10\x01\x12\n" +
	"\n" +
	"\x06DRIVER\x10\x02\"\xff\x03\n" +
	"\rCreateRequest\x120\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1c.software.CreateRequest.TypeR\x04type\x12?\n" +
	"\tlayerData\x18\x02 \x01(\v2!.software.CreateRequest.LayerDataR\tlayerData\x12B\n" +
	"\n" +
	"driverData\x18\x03 \x01(\v2\".software.CreateRequest.DriverDataR\n" +
	"driverData\x1a/\n" +
	"\tLayerData\x12\"\n" +
	"\fsoftwareUUID\x18\x01 \x01(\tR\fsoftwareUUID\x1a\xe6\x01\n" +
	"\n" +
	"DriverData\x12;\n" +
	"\x04type\x18\x01 \x01(\x0e2'.software.CreateRequest.DriverData.TypeR\x04type\x12\"\n" +
	"\fsoftwareUUID\x18\x02 \x01(\tR\fsoftwareUUID\x12\x1c\n" +
	"\tlayerUUID\x18\x03 \x01(\tR\tlayerUUID\x12\"\n" +
	"\x04font\x18\x04 \x01(\v2\x0e.software.FontR\x04font\"5\n" +
	"\x04Type\x12\n" +
	"\n" +
	"\x06RANDOM\x10\x00\x12\f\n" +
	"\bCARACTER\x10\x01\x12\b\n" +
	"\x04TEXT\x10\x02\x12\t\n" +
	"\x05IMAGE\x10\x03\"\x1d\n" +
	"\x04Type\x12\t\n" +
	"\x05LAYER\x10\x00\x12\n" +
	"\n" +
	"\x06DRIVER\x10\x01\"v\n" +
	"\x0eCreateResponse\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.software.CreateResponse.TypeR\x04type\x12\x12\n" +
	"\x04UUID\x18\x02 \x01(\tR\x04UUID\"\x1d\n" +
	"\x04Type\x12\t\n" +
	"\x05LAYER\x10\x00\x12\n" +
	"\n" +
	"\x06DRIVER\x10\x01\"\x9f\x03\n" +
	"\vLoadRequest\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.software.LoadRequest.TypeR\x04type\x12=\n" +
	"\timageData\x18\x02 \x01(\v2\x1f.software.LoadRequest.ImageDataR\timageData\x12=\n" +
	"\tcolorData\x18\x03 \x01(\v2\x1f.software.LoadRequest.ColorDataR\tcolorData\x12:\n" +
	"\bfontData\x18\x04 \x01(\v2\x1e.software.LoadRequest.FontDataR\bfontData\x1a\x1f\n" +
	"\tImageData\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x1a=\n" +
	"\tColorData\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tthemeName\x18\x02 \x01(\tR\tthemeName\x1a\x1e\n" +
	"\bFontData\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\x04Type\x12\t\n" +
	"\x05IMAGE\x10\x00\x12\t\n" +
	"\x05COLOR\x10\x01\x12\b\n" +
	"\x04FONT\x10\x02\"\xd7\x01\n" +
	"\fLoadResponse\x12/\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1b.software.LoadResponse.TypeR\x04type\x12%\n" +
	"\x05image\x18\x02 \x01(\v2\x0f.software.ImageR\x05image\x12#\n" +
	"\x05color\x18\x03 \x01(\v2\r.common.ColorR\x05color\x12\"\n" +
	"\x04font\x18\x04 \x01(\v2\x0e.software.FontR\x04font\"&\n" +
	"\x04Type\x12\t\n" +
	"\x05IMAGE\x10\x00\x12\t\n" +
	"\x05COLOR\x10\x01\x12\b\n" +
	"\x04FONT\x10\x02\"\x84\x01\n" +
	"\x05Image\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x04R\x05width\x12%\n" +
	"\x06colors\x18\x04 \x03(\v2\r.common.ColorR\x06colors\x12\x12\n" +
	"\x04mask\x18\x05 \x03(\x04R\x04mask\"\x9a\x01\n" +
	"\x05Theme\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\x06colors\x18\x02 \x03(\v2\x1b.software.Theme.ColorsEntryR\x06colors\x1aH\n" +
	"\vColorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.common.ColorR\x05value:\x028\x01\"\xfc\x01\n" +
	"\x04Font\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\x12;\n" +
	"\tcaracters\x18\x03 \x03(\v2\x1d.software.Font.CaractersEntryR\tcaracters\x1a4\n" +
	"\bCaracter\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x04R\x05width\x12\x12\n" +
	"\x04mask\x18\x02 \x03(\x04R\x04mask\x1aU\n" +
	"\x0eCaractersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.software.Font.CaracterR\x05value:\x028\x012\xc2\x01\n" +
	"\bSoftware\x12B\n" +
	"\aConnect\x12\x18.software.ConnectRequest\x1a\x19.software.ConnectResponse(\x010\x01\x12;\n" +
	"\x06Create\x12\x17.software.CreateRequest\x1a\x18.software.CreateResponse\x125\n" +
	"\x04Load\x12\x15.software.LoadRequest\x1a\x16.software.LoadResponseB6Z4github.com/richardlt/matrix/sdk-go/software;softwareb\x06proto3"

var (
	file_software_services_proto_rawDescOnce sync.Once
	file_software_services_proto_rawDescData []byte
)

func file_software_services_proto_rawDescGZIP() []byte {
	file_software_services_proto_rawDescOnce.Do(func() {
		file_software_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_software_services_proto_rawDesc), len(file_software_services_proto_rawDesc)))
	})
	return file_software_services_proto_rawDescData
}

var file_software_services_proto_enumTypes = make([]protoimpl.EnumInfo, 12)
var file_software_services_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_software_services_proto_goTypes = []any{
	(ConnectRequest_Type)(0),                   // 0: software.ConnectRequest.Type
	(ConnectRequest_SoftwareData_Action)(0),    // 1: software.ConnectRequest.SoftwareData.Action
	(ConnectRequest_LayerData_Action)(0),       // 2: software.ConnectRequest.LayerData.Action
	(ConnectRequest_DriverData_Action)(0),      // 3: software.ConnectRequest.DriverData.Action
	(ConnectResponse_Type)(0),                  // 4: software.ConnectResponse.Type
	(ConnectResponse_SoftwareData_Action)(0),   // 5: software.ConnectResponse.SoftwareData.Action
	(ConnectResponse_DriverData_Action)(0),     // 6: software.ConnectResponse.DriverData.Action
	(CreateRequest_Type)(0),                    // 7: software.CreateRequest.Type
	(CreateRequest_DriverData_Type)(0),         // 8: software.CreateRequest.DriverData.Type
	(CreateResponse_Type)(0),                   // 9: software.CreateResponse.Type
	(LoadRequest_Type)(0),                      // 10: software.LoadRequest.Type
	(LoadResponse_Type)(0),                     // 11: software.LoadResponse.Type
	(*ConnectRequest)(nil),                     // 12: software.ConnectRequest
	(*ConnectResponse)(nil),                    // 13: software.ConnectResponse
	(*CreateRequest)(nil),                      // 14: software.CreateRequest
	(*CreateResponse)(nil),                     // 15: software.CreateResponse
	(*LoadRequest)(nil),                        // 16: software.LoadRequest
	(*LoadResponse)(nil),                       // 17: software.LoadResponse
	(*Image)(nil),                              // 18: software.Image
	(*Theme)(nil),                              // 19: software.Theme
	(*Font)(nil),                               // 20: software.Font
	(*ConnectRequest_SoftwareData)(nil),        // 21: software.ConnectRequest.SoftwareData
	(*ConnectRequest_LayerData)(nil),           // 22: software.ConnectRequest.LayerData
	(*ConnectRequest_DriverData)(nil),          // 23: software.ConnectRequest.DriverData
	(*ConnectRequest_SoftwareData_Config)(nil), // 24: software.ConnectRequest.SoftwareData.Config
	(*ConnectResponse_SoftwareData)(nil),       // 25: software.ConnectResponse.SoftwareData
	(*ConnectResponse_DriverData)(nil),         // 26: software.ConnectResponse.DriverData
	(*CreateRequest_LayerData)(nil),            // 27: software.CreateRequest.LayerData
	(*CreateRequest_DriverData)(nil),           // 28: software.CreateRequest.DriverData
	(*LoadRequest_ImageData)(nil),              // 29: software.LoadRequest.ImageData
	(*LoadRequest_ColorData)(nil),              // 30: software.LoadRequest.ColorData
	(*LoadRequest_FontData)(nil),               // 31: software.LoadRequest.FontData
	nil,                                        // 32: software.Theme.ColorsEntry
	(*Font_Caracter)(nil),                      // 33: software.Font.Caracter
	nil,                                        // 34: software.Font.CaractersEntry
	(*common.Color)(nil),                       // 35: common.Color
	(*common.Coord)(nil),                       // 36: common.Coord
	(common.Command)(0),                        // 37: common.Command
}
var file_software_services_proto_depIdxs = []int32{
	0,  // 0: software.ConnectRequest.type:type_name -> software.ConnectRequest.Type
	21, // 1: software.ConnectRequest.softwareData:type_name -> software.ConnectRequest.SoftwareData
	22, // 2: software.ConnectRequest.layerData:type_name -> software.ConnectRequest.LayerData
	23, // 3: software.ConnectRequest.driverData:type_name -> software.ConnectRequest.DriverData
	4,  // 4: software.ConnectResponse.type:type_name -> software.ConnectResponse.Type
	25, // 5: software.ConnectResponse.softwareData:type_name -> software.ConnectResponse.SoftwareData
	26, // 6: software.ConnectResponse.driverData:type_name -> software.ConnectResponse.DriverData
	7,  // 7: software.CreateRequest.type:type_name -> software.CreateRequest.Type
	27, // 8: software.CreateRequest.layerData:type_name -> software.CreateRequest.LayerData
	28, // 9: software.CreateRequest.driverData:type_name -> software.CreateRequest.DriverData
	9,  // 10: software.CreateResponse.type:type_name -> software.CreateResponse.Type
	10, // 11: software.LoadRequest.type:type_name -> software.LoadRequest.Type
	29, // 12: software.LoadRequest.imageData:type_name -> software.LoadRequest.ImageData
	30, // 13: software.LoadRequest.colorData:type_name -> software.LoadRequest.ColorData
	31, // 14: software.LoadRequest.fontData:type_name -> software.LoadRequest.FontData
	11, // 15: software.LoadResponse.type:type_name -> software.LoadResponse.Type
	18, // 16: software.LoadResponse.image:type_name -> software.Image
	35, // 17: software.LoadResponse.color:type_name -> common.Color
	20, // 18: software.LoadResponse.font:type_name -> software.Font
	35, // 19: software.Image.colors:type_name -> common.Color
	32, // 20: software.Theme.colors:type_name -> software.Theme.ColorsEntry
	34, // 21: software.Font.caracters:type_name -> software.Font.CaractersEntry
	1,  // 22: software.ConnectRequest.SoftwareData.action:type_name -> software.ConnectRequest.SoftwareData.Action
	24, // 23: software.ConnectRequest.SoftwareData.config:type_name -> software.ConnectRequest.SoftwareData.Config
	2,  // 24: software.ConnectRequest.LayerData.action:type_name -> software.ConnectRequest.LayerData.Action
	36, // 25: software.ConnectRequest.LayerData.coord:type_name -> common.Coord
	35, // 26: software.ConnectRequest.LayerData.color:type_name -> common.Color
	3,  // 27: software.ConnectRequest.DriverData.action:type_name -> software.ConnectRequest.DriverData.Action
	35, // 28: software.ConnectRequest.DriverData.color:type_name -> common.Color
	35, // 29: software.ConnectRequest.DriverData.background:type_name -> common.Color
	36, // 30: software.ConnectRequest.DriverData.coord:type_name -> common.Coord
	18, // 31: software.ConnectRequest.DriverData.image:type_name -> software.Image
	18, // 32: software.ConnectRequest.SoftwareData.Config.logo:type_name -> software.Image
	5,  // 33: software.ConnectResponse.SoftwareData.action:type_name -> software.ConnectResponse.SoftwareData.Action
	37, // 34: software.ConnectResponse.SoftwareData.command:type_name -> common.Command
	6,  // 35: software.ConnectResponse.DriverData.action:type_name -> software.ConnectResponse.DriverData.Action
	8,  // 36: software.CreateRequest.DriverData.type:type_name -> software.CreateRequest.DriverData.Type
	20, // 37: software.CreateRequest.DriverData.font:type_name -> software.Font
	35, // 38: software.Theme.ColorsEntry.value:type_name -> common.Color
	33, // 39: software.Font.CaractersEntry.value:type_name -> software.Font.Caracter
	12, // 40: software.Software.Connect:input_type -> software.ConnectRequest
	14, // 41: software.Software.Create:input_type -> software.CreateRequest
	16, // 42: software.Software.Load:input_type -> software.LoadRequest
	13, // 43: software.Software.Connect:output_type -> software.ConnectResponse
	15, // 44: software.Software.Create:output_type -> software.CreateResponse
	17, // 45: software.Software.Load:output_type -> software.LoadResponse
	43, // [43:46] is the sub-list for method output_type
	40, // [40:43] is the sub-list for method input_type
	40, // [40:40] is the sub-list for extension type_name
	40, // [40:40] is the sub-list for extension extendee
	0,  // [0:40] is the sub-list for field type_name
}

func init() { file_software_services_proto_init() }
func file_software_services_proto_init() {
	if File_software_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_software_services_proto_rawDesc), len(file_software_services_proto_rawDesc)),
			NumEnums:      12,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_software_services_proto_goTypes,
		DependencyIndexes: file_software_services_proto_depIdxs,
		EnumInfos:         file_software_services_proto_enumTypes,
		MessageInfos:      file_software_services_proto_msgTypes,
	}.Build()
	File_software_services_proto = out.File
	file_software_services_proto_goTypes = nil
	file_software_services_proto_depIdxs = nil
}
