package-name: "matrix"
architecture: "armhf"
binary-file: "./matrix-package/matrix-linux-arm-7"
copy-files:
  - "./matrix-package/themes/*:/var/lib/matrix/themes"
  - "./matrix-package/fonts/*:/var/lib/matrix/fonts"
  - "./matrix-package/images/*:/var/lib/matrix/images"
  - "./matrix-package/animations/*:/var/lib/matrix/animations"
  - "./matrix-package/gamepad/public/*:/var/lib/matrix/gamepad/public"
  - "./matrix-package/emulator/public/*:/var/lib/matrix/emulator/public"
version: "0.0.1"
description: "Matrix debian package"
maintainer: "richard.le.terrier@gmail.com"
systemd-configuration:
  user: "root"
  after: network.target
  args: ["start", "--log-level", "info", "--gamepad-port", "80", "core", "device", "gamepad", "emulator", "demo", "zigzag", "yumyum", "clock", "draw", "blocks", "getout", "animate", "light"]
  stop-command: /bin/kill $MAINPID
  restart: always
  wanted-by: multi-user.target
  working-directory: "/var/lib/matrix"