version: v1.0
name: release
parameters:
  tagLevel:
    type: list
    default: major;minor;patch
jobs:
- job: release
  steps:
  - checkout: '{{.cds.workspace}}'
  - gitTag:
      path: '{{.cds.workspace}}'
      tagLevel: '{{.cds.pip.tagLevel}}'
      tagMessage: Matrix release
  - artifactDownload:
      path: '{{.cds.workspace}}'
      pattern: matrix.deb|matrix.zip
      tag: '{{.cds.version}}'
  - script:
    - TAG=`git describe --abbrev=0 --tags`
    - worker export tag $TAG
  - release:
      artifacts: matrix.deb,matrix.zip
      releaseNote: Matrix release {{.cds.build.tag}}
      tag: '{{.cds.build.tag}}'
      title: '{{.cds.build.tag}}'
  requirements:
  - binary: git
  - binary: gpg