// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/types.proto

/*
Package common is a generated protocol buffer package.

It is generated from these files:
	common/types.proto

It has these top-level messages:
	Color
	Layer
	Coord
	Frame
*/
package common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Command int32

const (
	Command_UP_UP       Command = 0
	Command_UP_DOWN     Command = 1
	Command_RIGHT_UP    Command = 2
	Command_RIGHT_DOWN  Command = 3
	Command_LEFT_UP     Command = 4
	Command_LEFT_DOWN   Command = 5
	Command_DOWN_UP     Command = 6
	Command_DOWN_DOWN   Command = 7
	Command_A_UP        Command = 8
	Command_A_DOWN      Command = 9
	Command_B_UP        Command = 10
	Command_B_DOWN      Command = 11
	Command_X_UP        Command = 12
	Command_X_DOWN      Command = 13
	Command_Y_UP        Command = 14
	Command_Y_DOWN      Command = 15
	Command_START_UP    Command = 16
	Command_START_DOWN  Command = 17
	Command_SELECT_UP   Command = 18
	Command_SELECT_DOWN Command = 19
	Command_L_UP        Command = 20
	Command_L_DOWN      Command = 21
	Command_R_UP        Command = 22
	Command_R_DOWN      Command = 23
)

var Command_name = map[int32]string{
	0:  "UP_UP",
	1:  "UP_DOWN",
	2:  "RIGHT_UP",
	3:  "RIGHT_DOWN",
	4:  "LEFT_UP",
	5:  "LEFT_DOWN",
	6:  "DOWN_UP",
	7:  "DOWN_DOWN",
	8:  "A_UP",
	9:  "A_DOWN",
	10: "B_UP",
	11: "B_DOWN",
	12: "X_UP",
	13: "X_DOWN",
	14: "Y_UP",
	15: "Y_DOWN",
	16: "START_UP",
	17: "START_DOWN",
	18: "SELECT_UP",
	19: "SELECT_DOWN",
	20: "L_UP",
	21: "L_DOWN",
	22: "R_UP",
	23: "R_DOWN",
}
var Command_value = map[string]int32{
	"UP_UP":       0,
	"UP_DOWN":     1,
	"RIGHT_UP":    2,
	"RIGHT_DOWN":  3,
	"LEFT_UP":     4,
	"LEFT_DOWN":   5,
	"DOWN_UP":     6,
	"DOWN_DOWN":   7,
	"A_UP":        8,
	"A_DOWN":      9,
	"B_UP":        10,
	"B_DOWN":      11,
	"X_UP":        12,
	"X_DOWN":      13,
	"Y_UP":        14,
	"Y_DOWN":      15,
	"START_UP":    16,
	"START_DOWN":  17,
	"SELECT_UP":   18,
	"SELECT_DOWN": 19,
	"L_UP":        20,
	"L_DOWN":      21,
	"R_UP":        22,
	"R_DOWN":      23,
}

func (x Command) String() string {
	return proto.EnumName(Command_name, int32(x))
}
func (Command) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Color struct {
	R uint64 `protobuf:"varint,1,opt,name=r" json:"r,omitempty"`
	G uint64 `protobuf:"varint,2,opt,name=g" json:"g,omitempty"`
	B uint64 `protobuf:"varint,3,opt,name=b" json:"b,omitempty"`
	A uint64 `protobuf:"varint,4,opt,name=a" json:"a,omitempty"`
}

func (m *Color) Reset()                    { *m = Color{} }
func (m *Color) String() string            { return proto.CompactTextString(m) }
func (*Color) ProtoMessage()               {}
func (*Color) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Color) GetR() uint64 {
	if m != nil {
		return m.R
	}
	return 0
}

func (m *Color) GetG() uint64 {
	if m != nil {
		return m.G
	}
	return 0
}

func (m *Color) GetB() uint64 {
	if m != nil {
		return m.B
	}
	return 0
}

func (m *Color) GetA() uint64 {
	if m != nil {
		return m.A
	}
	return 0
}

type Layer struct {
	Uuid string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
}

func (m *Layer) Reset()                    { *m = Layer{} }
func (m *Layer) String() string            { return proto.CompactTextString(m) }
func (*Layer) ProtoMessage()               {}
func (*Layer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Layer) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type Coord struct {
	X uint64 `protobuf:"varint,1,opt,name=x" json:"x,omitempty"`
	Y uint64 `protobuf:"varint,2,opt,name=y" json:"y,omitempty"`
}

func (m *Coord) Reset()                    { *m = Coord{} }
func (m *Coord) String() string            { return proto.CompactTextString(m) }
func (*Coord) ProtoMessage()               {}
func (*Coord) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Coord) GetX() uint64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Coord) GetY() uint64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Frame struct {
	Pixels []*Color `protobuf:"bytes,1,rep,name=pixels" json:"pixels,omitempty"`
}

func (m *Frame) Reset()                    { *m = Frame{} }
func (m *Frame) String() string            { return proto.CompactTextString(m) }
func (*Frame) ProtoMessage()               {}
func (*Frame) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Frame) GetPixels() []*Color {
	if m != nil {
		return m.Pixels
	}
	return nil
}

func init() {
	proto.RegisterType((*Color)(nil), "common.Color")
	proto.RegisterType((*Layer)(nil), "common.Layer")
	proto.RegisterType((*Coord)(nil), "common.Coord")
	proto.RegisterType((*Frame)(nil), "common.Frame")
	proto.RegisterEnum("common.Command", Command_name, Command_value)
}

func init() { proto.RegisterFile("common/types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x91, 0xcb, 0x6a, 0xf2, 0x50,
	0x14, 0x46, 0xff, 0x68, 0x12, 0xcd, 0x8e, 0xb7, 0x7f, 0xf7, 0x16, 0xe8, 0x44, 0x52, 0x0a, 0xd2,
	0x41, 0x0a, 0xed, 0x03, 0x14, 0xb5, 0xda, 0x16, 0x42, 0x2b, 0x51, 0xa9, 0x8e, 0x24, 0xd6, 0x20,
	0x82, 0xf1, 0x48, 0x54, 0x30, 0x8f, 0xd6, 0xb7, 0x2b, 0xdf, 0x3e, 0x3a, 0x3b, 0x6b, 0x2d, 0xdd,
	0x7c, 0x10, 0xe2, 0x1f, 0x95, 0xa6, 0x6a, 0xf3, 0xb8, 0xcf, 0xb7, 0xc9, 0x2e, 0xd8, 0x66, 0x6a,
	0xaf, 0xd8, 0xd6, 0xce, 0x7f, 0x21, 0xab, 0xab, 0xd6, 0x2a, 0xe3, 0x0a, 0x19, 0x99, 0x67, 0x34,
	0x8d, 0x96, 0x19, 0x19, 0x42, 0x4b, 0xaf, 0xa0, 0x69, 0x09, 0x9a, 0x7b, 0x45, 0x4d, 0x73, 0x50,
	0xec, 0x99, 0x9a, 0x62, 0xff, 0x96, 0xac, 0x30, 0xce, 0x93, 0x8c, 0x99, 0xcc, 0xc3, 0x61, 0xb5,
	0x90, 0x1b, 0x4e, 0x24, 0x6f, 0xff, 0x0e, 0xd7, 0x55, 0xb6, 0xc0, 0x7f, 0x8e, 0xe7, 0xeb, 0x47,
	0x50, 0x7e, 0xbe, 0x9e, 0xfb, 0x01, 0x59, 0xfd, 0x2c, 0x4e, 0x13, 0xbe, 0x27, 0x7b, 0xbb, 0x3a,
	0x26, 0xeb, 0x9d, 0x67, 0x34, 0x8b, 0x2d, 0xf7, 0xa9, 0x1a, 0xe8, 0x91, 0x81, 0x2c, 0x8c, 0x4e,
	0xf1, 0xe1, 0xb7, 0x40, 0xa5, 0xae, 0x4a, 0xd3, 0x78, 0xb3, 0x60, 0x87, 0xac, 0xf1, 0x60, 0x36,
	0x1e, 0x34, 0xfe, 0xb1, 0x4b, 0xa5, 0xf1, 0x60, 0xf6, 0xfa, 0xf5, 0xfd, 0xd9, 0x30, 0xb8, 0x42,
	0xe5, 0xe8, 0xe3, 0xed, 0x7d, 0x84, 0x54, 0xe0, 0x1a, 0x91, 0x26, 0xa9, 0x45, 0xfc, 0x34, 0xec,
	0xf5, 0x25, 0x9a, 0x5c, 0x25, 0x47, 0x40, 0x9a, 0x85, 0x86, 0x17, 0x9a, 0x8d, 0x26, 0x20, 0xad,
	0xc4, 0x65, 0x32, 0xdb, 0x08, 0x65, 0x26, 0xb2, 0xdb, 0xda, 0x3a, 0xb0, 0x1d, 0x58, 0x82, 0xed,
	0x68, 0xeb, 0xc2, 0x4e, 0x60, 0x2b, 0xb0, 0x13, 0x6d, 0xab, 0xb0, 0x53, 0xd8, 0x1a, 0xec, 0x54,
	0xdb, 0x3a, 0xd6, 0x0e, 0x47, 0xed, 0x48, 0x06, 0x35, 0xb0, 0x56, 0x93, 0xd4, 0xff, 0x18, 0x31,
	0xec, 0x85, 0xbd, 0xae, 0x64, 0xe6, 0x3a, 0xb9, 0x27, 0x94, 0x7e, 0x81, 0x9b, 0x21, 0xd2, 0x25,
	0x6e, 0x86, 0xda, 0x5e, 0xc1, 0x46, 0xb0, 0xd7, 0xb0, 0x91, 0xb6, 0x37, 0x73, 0x5b, 0xbe, 0xfe,
	0xf3, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x16, 0x66, 0x36, 0x13, 0x02, 0x00, 0x00,
}
