// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: display/services.proto

package display

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Display_Connect_FullMethodName = "/display.Display/Connect"
)

// DisplayClient is the client API for Display service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DisplayClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Response], error)
}

type displayClient struct {
	cc grpc.ClientConnInterface
}

func NewDisplayClient(cc grpc.ClientConnInterface) DisplayClient {
	return &displayClient{cc}
}

func (c *displayClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Display_ServiceDesc.Streams[0], Display_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, Response]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Display_ConnectClient = grpc.BidiStreamingClient[Request, Response]

// DisplayServer is the server API for Display service.
// All implementations must embed UnimplementedDisplayServer
// for forward compatibility.
type DisplayServer interface {
	Connect(grpc.BidiStreamingServer[Request, Response]) error
	mustEmbedUnimplementedDisplayServer()
}

// UnimplementedDisplayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDisplayServer struct{}

func (UnimplementedDisplayServer) Connect(grpc.BidiStreamingServer[Request, Response]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedDisplayServer) mustEmbedUnimplementedDisplayServer() {}
func (UnimplementedDisplayServer) testEmbeddedByValue()                 {}

// UnsafeDisplayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DisplayServer will
// result in compilation errors.
type UnsafeDisplayServer interface {
	mustEmbedUnimplementedDisplayServer()
}

func RegisterDisplayServer(s grpc.ServiceRegistrar, srv DisplayServer) {
	// If the following call panics, it indicates UnimplementedDisplayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Display_ServiceDesc, srv)
}

func _Display_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DisplayServer).Connect(&grpc.GenericServerStream[Request, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Display_ConnectServer = grpc.BidiStreamingServer[Request, Response]

// Display_ServiceDesc is the grpc.ServiceDesc for Display service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Display_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "display.Display",
	HandlerType: (*DisplayServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Display_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "display/services.proto",
}
