// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.1
// source: display/services.proto

package display

import (
	common "github.com/richardlt/matrix/sdk-go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request_Type int32

const (
	Request_PING Request_Type = 0
)

// Enum value maps for Request_Type.
var (
	Request_Type_name = map[int32]string{
		0: "PING",
	}
	Request_Type_value = map[string]int32{
		"PING": 0,
	}
)

func (x Request_Type) Enum() *Request_Type {
	p := new(Request_Type)
	*p = x
	return p
}

func (x Request_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Request_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_display_services_proto_enumTypes[0].Descriptor()
}

func (Request_Type) Type() protoreflect.EnumType {
	return &file_display_services_proto_enumTypes[0]
}

func (x Request_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Request_Type.Descriptor instead.
func (Request_Type) EnumDescriptor() ([]byte, []int) {
	return file_display_services_proto_rawDescGZIP(), []int{0, 0}
}

type Response_Type int32

const (
	Response_PING    Response_Type = 0
	Response_DISPLAY Response_Type = 1
)

// Enum value maps for Response_Type.
var (
	Response_Type_name = map[int32]string{
		0: "PING",
		1: "DISPLAY",
	}
	Response_Type_value = map[string]int32{
		"PING":    0,
		"DISPLAY": 1,
	}
)

func (x Response_Type) Enum() *Response_Type {
	p := new(Response_Type)
	*p = x
	return p
}

func (x Response_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Response_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_display_services_proto_enumTypes[1].Descriptor()
}

func (Response_Type) Type() protoreflect.EnumType {
	return &file_display_services_proto_enumTypes[1]
}

func (x Response_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Response_Type.Descriptor instead.
func (Response_Type) EnumDescriptor() ([]byte, []int) {
	return file_display_services_proto_rawDescGZIP(), []int{1, 0}
}

type Response_DisplayData_Action int32

const (
	Response_DisplayData_FRAMES Response_DisplayData_Action = 0
)

// Enum value maps for Response_DisplayData_Action.
var (
	Response_DisplayData_Action_name = map[int32]string{
		0: "FRAMES",
	}
	Response_DisplayData_Action_value = map[string]int32{
		"FRAMES": 0,
	}
)

func (x Response_DisplayData_Action) Enum() *Response_DisplayData_Action {
	p := new(Response_DisplayData_Action)
	*p = x
	return p
}

func (x Response_DisplayData_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Response_DisplayData_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_display_services_proto_enumTypes[2].Descriptor()
}

func (Response_DisplayData_Action) Type() protoreflect.EnumType {
	return &file_display_services_proto_enumTypes[2]
}

func (x Response_DisplayData_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Response_DisplayData_Action.Descriptor instead.
func (Response_DisplayData_Action) EnumDescriptor() ([]byte, []int) {
	return file_display_services_proto_rawDescGZIP(), []int{1, 0, 0}
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Request_Type           `protobuf:"varint,1,opt,name=type,proto3,enum=display.Request_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_display_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_display_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_display_services_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetType() Request_Type {
	if x != nil {
		return x.Type
	}
	return Request_PING
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Response_Type          `protobuf:"varint,1,opt,name=type,proto3,enum=display.Response_Type" json:"type,omitempty"`
	DisplayData   *Response_DisplayData  `protobuf:"bytes,2,opt,name=displayData,proto3" json:"displayData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_display_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_display_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_display_services_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetType() Response_Type {
	if x != nil {
		return x.Type
	}
	return Response_PING
}

func (x *Response) GetDisplayData() *Response_DisplayData {
	if x != nil {
		return x.DisplayData
	}
	return nil
}

type Response_DisplayData struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Action        Response_DisplayData_Action `protobuf:"varint,1,opt,name=action,proto3,enum=display.Response_DisplayData_Action" json:"action,omitempty"`
	Frames        []*common.Frame             `protobuf:"bytes,2,rep,name=frames,proto3" json:"frames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response_DisplayData) Reset() {
	*x = Response_DisplayData{}
	mi := &file_display_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response_DisplayData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_DisplayData) ProtoMessage() {}

func (x *Response_DisplayData) ProtoReflect() protoreflect.Message {
	mi := &file_display_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_DisplayData.ProtoReflect.Descriptor instead.
func (*Response_DisplayData) Descriptor() ([]byte, []int) {
	return file_display_services_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Response_DisplayData) GetAction() Response_DisplayData_Action {
	if x != nil {
		return x.Action
	}
	return Response_DisplayData_FRAMES
}

func (x *Response_DisplayData) GetFrames() []*common.Frame {
	if x != nil {
		return x.Frames
	}
	return nil
}

var File_display_services_proto protoreflect.FileDescriptor

const file_display_services_proto_rawDesc = "" +
	"\n" +
	"\x16display/services.proto\x12\adisplay\x1a\x12common/types.proto\"F\n" +
	"\aRequest\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.display.Request.TypeR\x04type\"\x10\n" +
	"\x04Type\x12\b\n" +
	"\x04PING\x10\x00\"\xa1\x02\n" +
	"\bResponse\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.display.Response.TypeR\x04type\x12?\n" +
	"\vdisplayData\x18\x02 \x01(\v2\x1d.display.Response.DisplayDataR\vdisplayData\x1a\x88\x01\n" +
	"\vDisplayData\x12<\n" +
	"\x06action\x18\x01 \x01(\x0e2$.display.Response.DisplayData.ActionR\x06action\x12%\n" +
	"\x06frames\x18\x02 \x03(\v2\r.common.FrameR\x06frames\"\x14\n" +
	"\x06Action\x12\n" +
	"\n" +
	"\x06FRAMES\x10\x00\"\x1d\n" +
	"\x04Type\x12\b\n" +
	"\x04PING\x10\x00\x12\v\n" +
	"\aDISPLAY\x10\x012=\n" +
	"\aDisplay\x122\n" +
	"\aConnect\x12\x10.display.Request\x1a\x11.display.Response(\x010\x01B4Z2github.com/richardlt/matrix/sdk-go/display;displayb\x06proto3"

var (
	file_display_services_proto_rawDescOnce sync.Once
	file_display_services_proto_rawDescData []byte
)

func file_display_services_proto_rawDescGZIP() []byte {
	file_display_services_proto_rawDescOnce.Do(func() {
		file_display_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_display_services_proto_rawDesc), len(file_display_services_proto_rawDesc)))
	})
	return file_display_services_proto_rawDescData
}

var file_display_services_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_display_services_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_display_services_proto_goTypes = []any{
	(Request_Type)(0),                // 0: display.Request.Type
	(Response_Type)(0),               // 1: display.Response.Type
	(Response_DisplayData_Action)(0), // 2: display.Response.DisplayData.Action
	(*Request)(nil),                  // 3: display.Request
	(*Response)(nil),                 // 4: display.Response
	(*Response_DisplayData)(nil),     // 5: display.Response.DisplayData
	(*common.Frame)(nil),             // 6: common.Frame
}
var file_display_services_proto_depIdxs = []int32{
	0, // 0: display.Request.type:type_name -> display.Request.Type
	1, // 1: display.Response.type:type_name -> display.Response.Type
	5, // 2: display.Response.displayData:type_name -> display.Response.DisplayData
	2, // 3: display.Response.DisplayData.action:type_name -> display.Response.DisplayData.Action
	6, // 4: display.Response.DisplayData.frames:type_name -> common.Frame
	3, // 5: display.Display.Connect:input_type -> display.Request
	4, // 6: display.Display.Connect:output_type -> display.Response
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_display_services_proto_init() }
func file_display_services_proto_init() {
	if File_display_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_display_services_proto_rawDesc), len(file_display_services_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_display_services_proto_goTypes,
		DependencyIndexes: file_display_services_proto_depIdxs,
		EnumInfos:         file_display_services_proto_enumTypes,
		MessageInfos:      file_display_services_proto_msgTypes,
	}.Build()
	File_display_services_proto = out.File
	file_display_services_proto_goTypes = nil
	file_display_services_proto_depIdxs = nil
}
