// Code generated by protoc-gen-go. DO NOT EDIT.
// source: display/services.proto

/*
Package display is a generated protocol buffer package.

It is generated from these files:
	display/services.proto

It has these top-level messages:
	Request
	Response
*/
package display

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "github.com/richardlt/matrix/sdk-go/common"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request_Type int32

const (
	Request_PING Request_Type = 0
)

var Request_Type_name = map[int32]string{
	0: "PING",
}
var Request_Type_value = map[string]int32{
	"PING": 0,
}

func (x Request_Type) String() string {
	return proto.EnumName(Request_Type_name, int32(x))
}
func (Request_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Response_Type int32

const (
	Response_PING    Response_Type = 0
	Response_DISPLAY Response_Type = 1
)

var Response_Type_name = map[int32]string{
	0: "PING",
	1: "DISPLAY",
}
var Response_Type_value = map[string]int32{
	"PING":    0,
	"DISPLAY": 1,
}

func (x Response_Type) String() string {
	return proto.EnumName(Response_Type_name, int32(x))
}
func (Response_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Response_DisplayData_Action int32

const (
	Response_DisplayData_FRAMES Response_DisplayData_Action = 0
)

var Response_DisplayData_Action_name = map[int32]string{
	0: "FRAMES",
}
var Response_DisplayData_Action_value = map[string]int32{
	"FRAMES": 0,
}

func (x Response_DisplayData_Action) String() string {
	return proto.EnumName(Response_DisplayData_Action_name, int32(x))
}
func (Response_DisplayData_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0, 0}
}

type Request struct {
	Type Request_Type `protobuf:"varint,1,opt,name=type,enum=display.Request_Type" json:"type,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetType() Request_Type {
	if m != nil {
		return m.Type
	}
	return Request_PING
}

type Response struct {
	Type        Response_Type         `protobuf:"varint,1,opt,name=type,enum=display.Response_Type" json:"type,omitempty"`
	DisplayData *Response_DisplayData `protobuf:"bytes,2,opt,name=displayData" json:"displayData,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetType() Response_Type {
	if m != nil {
		return m.Type
	}
	return Response_PING
}

func (m *Response) GetDisplayData() *Response_DisplayData {
	if m != nil {
		return m.DisplayData
	}
	return nil
}

type Response_DisplayData struct {
	Action Response_DisplayData_Action `protobuf:"varint,1,opt,name=action,enum=display.Response_DisplayData_Action" json:"action,omitempty"`
	Frames []*common.Frame             `protobuf:"bytes,2,rep,name=frames" json:"frames,omitempty"`
}

func (m *Response_DisplayData) Reset()                    { *m = Response_DisplayData{} }
func (m *Response_DisplayData) String() string            { return proto.CompactTextString(m) }
func (*Response_DisplayData) ProtoMessage()               {}
func (*Response_DisplayData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *Response_DisplayData) GetAction() Response_DisplayData_Action {
	if m != nil {
		return m.Action
	}
	return Response_DisplayData_FRAMES
}

func (m *Response_DisplayData) GetFrames() []*common.Frame {
	if m != nil {
		return m.Frames
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "display.Request")
	proto.RegisterType((*Response)(nil), "display.Response")
	proto.RegisterType((*Response_DisplayData)(nil), "display.Response.DisplayData")
	proto.RegisterEnum("display.Request_Type", Request_Type_name, Request_Type_value)
	proto.RegisterEnum("display.Response_Type", Response_Type_name, Response_Type_value)
	proto.RegisterEnum("display.Response_DisplayData_Action", Response_DisplayData_Action_name, Response_DisplayData_Action_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Display service

type DisplayClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (Display_ConnectClient, error)
}

type displayClient struct {
	cc *grpc.ClientConn
}

func NewDisplayClient(cc *grpc.ClientConn) DisplayClient {
	return &displayClient{cc}
}

func (c *displayClient) Connect(ctx context.Context, opts ...grpc.CallOption) (Display_ConnectClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Display_serviceDesc.Streams[0], c.cc, "/display.Display/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &displayConnectClient{stream}
	return x, nil
}

type Display_ConnectClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type displayConnectClient struct {
	grpc.ClientStream
}

func (x *displayConnectClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *displayConnectClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Display service

type DisplayServer interface {
	Connect(Display_ConnectServer) error
}

func RegisterDisplayServer(s *grpc.Server, srv DisplayServer) {
	s.RegisterService(&_Display_serviceDesc, srv)
}

func _Display_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DisplayServer).Connect(&displayConnectServer{stream})
}

type Display_ConnectServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type displayConnectServer struct {
	grpc.ServerStream
}

func (x *displayConnectServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *displayConnectServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Display_serviceDesc = grpc.ServiceDesc{
	ServiceName: "display.Display",
	HandlerType: (*DisplayServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Display_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "display/services.proto",
}

func init() { proto.RegisterFile("display/services.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x51, 0x4b, 0xfb, 0x30,
	0x14, 0xc5, 0x97, 0xfd, 0x47, 0x3b, 0x6e, 0xf9, 0x4b, 0x0d, 0x3a, 0xc6, 0x60, 0x30, 0x8a, 0x42,
	0x15, 0x4c, 0xa5, 0xe2, 0x9b, 0x22, 0xc3, 0x39, 0x19, 0xa8, 0x8c, 0xcc, 0x17, 0x1f, 0xb3, 0x2e,
	0x6e, 0xc1, 0xb5, 0xa9, 0x49, 0x26, 0xee, 0x1b, 0xf8, 0x35, 0xfc, 0xa6, 0xb2, 0x35, 0x62, 0xdd,
	0xc0, 0xc7, 0xdc, 0x73, 0xce, 0xef, 0x86, 0x73, 0xa1, 0x31, 0x11, 0x3a, 0x9f, 0xb3, 0x65, 0xa4,
	0xb9, 0x7a, 0x13, 0x09, 0xd7, 0x24, 0x57, 0xd2, 0x48, 0xec, 0xda, 0x79, 0xeb, 0x7c, 0x2a, 0xcc,
	0x6c, 0x31, 0x26, 0x89, 0x4c, 0x23, 0x25, 0x92, 0x19, 0x53, 0x93, 0xb9, 0x89, 0x52, 0x66, 0x94,
	0x78, 0x8f, 0xf4, 0xe4, 0xe5, 0x64, 0x2a, 0xa3, 0x44, 0xa6, 0xa9, 0xcc, 0x22, 0xb3, 0xcc, 0xbf,
	0xf3, 0x41, 0x1f, 0x5c, 0xca, 0x5f, 0x17, 0x5c, 0x1b, 0x7c, 0x04, 0xb5, 0x95, 0xd2, 0x44, 0x1d,
	0x14, 0xee, 0xc4, 0xfb, 0xc4, 0x92, 0x89, 0xd5, 0xc9, 0xe3, 0x32, 0xe7, 0x74, 0x6d, 0x09, 0x7c,
	0xa8, 0xad, 0x5e, 0xb8, 0x0e, 0xb5, 0xe1, 0xe0, 0xe1, 0xd6, 0xaf, 0x04, 0x9f, 0x55, 0xa8, 0x53,
	0xae, 0x73, 0x99, 0x69, 0x8e, 0x8f, 0x7f, 0x91, 0x1a, 0x25, 0x52, 0x61, 0x28, 0xa1, 0xf0, 0x15,
	0x78, 0x56, 0xee, 0x31, 0xc3, 0x9a, 0xd5, 0x0e, 0x0a, 0xbd, 0xb8, 0xbd, 0x1d, 0xe9, 0xfd, 0x98,
	0x68, 0x39, 0xd1, 0xfa, 0x40, 0xe0, 0x95, 0x44, 0x7c, 0x01, 0x0e, 0x4b, 0x8c, 0x90, 0x99, 0x5d,
	0x7f, 0xf0, 0x27, 0x8b, 0x74, 0xd7, 0x5e, 0x6a, 0x33, 0xf8, 0x10, 0x9c, 0x67, 0xc5, 0x52, 0xae,
	0x9b, 0xd5, 0xce, 0xbf, 0xd0, 0x8b, 0xff, 0x93, 0xa2, 0x34, 0xd2, 0x5f, 0x4d, 0xa9, 0x15, 0x83,
	0x3d, 0x70, 0x8a, 0x20, 0x06, 0x70, 0xfa, 0xb4, 0x7b, 0x7f, 0x33, 0xf2, 0x2b, 0x41, 0x7b, 0xb3,
	0x16, 0xec, 0x81, 0xdb, 0x1b, 0x8c, 0x86, 0x77, 0xdd, 0x27, 0x1f, 0xc5, 0x97, 0xe0, 0xda, 0xcd,
	0x38, 0x06, 0xf7, 0x5a, 0x66, 0x19, 0x4f, 0x0c, 0xf6, 0x37, 0x8b, 0x6e, 0xed, 0x6e, 0xfd, 0x38,
	0x44, 0xa7, 0x68, 0xec, 0xac, 0x2f, 0x76, 0xf6, 0x15, 0x00, 0x00, 0xff, 0xff, 0x5c, 0xcc, 0x46,
	0xc7, 0x0b, 0x02, 0x00, 0x00,
}
