// Code generated by protoc-gen-go. DO NOT EDIT.
// source: player/services.proto

package player

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "github.com/richardlt/matrix/sdk-go/common"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request_Type int32

const (
	Request_PING   Request_Type = 0
	Request_PLAYER Request_Type = 1
)

var Request_Type_name = map[int32]string{
	0: "PING",
	1: "PLAYER",
}

var Request_Type_value = map[string]int32{
	"PING":   0,
	"PLAYER": 1,
}

func (x Request_Type) String() string {
	return proto.EnumName(Request_Type_name, int32(x))
}

func (Request_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2d2f3dcd4c58ab80, []int{0, 0}
}

type Request_PlayerData_Action int32

const (
	Request_PlayerData_COMMAND Request_PlayerData_Action = 0
)

var Request_PlayerData_Action_name = map[int32]string{
	0: "COMMAND",
}

var Request_PlayerData_Action_value = map[string]int32{
	"COMMAND": 0,
}

func (x Request_PlayerData_Action) String() string {
	return proto.EnumName(Request_PlayerData_Action_name, int32(x))
}

func (Request_PlayerData_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2d2f3dcd4c58ab80, []int{0, 0, 0}
}

type Response_Type int32

const (
	Response_PING Response_Type = 0
)

var Response_Type_name = map[int32]string{
	0: "PING",
}

var Response_Type_value = map[string]int32{
	"PING": 0,
}

func (x Response_Type) String() string {
	return proto.EnumName(Response_Type_name, int32(x))
}

func (Response_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2d2f3dcd4c58ab80, []int{1, 0}
}

type Request struct {
	Type                 Request_Type        `protobuf:"varint,1,opt,name=type,proto3,enum=player.Request_Type" json:"type,omitempty"`
	PlayerData           *Request_PlayerData `protobuf:"bytes,2,opt,name=playerData,proto3" json:"playerData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d2f3dcd4c58ab80, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetType() Request_Type {
	if m != nil {
		return m.Type
	}
	return Request_PING
}

func (m *Request) GetPlayerData() *Request_PlayerData {
	if m != nil {
		return m.PlayerData
	}
	return nil
}

type Request_PlayerData struct {
	Action               Request_PlayerData_Action `protobuf:"varint,1,opt,name=action,proto3,enum=player.Request_PlayerData_Action" json:"action,omitempty"`
	Slot                 uint64                    `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	Command              common.Command            `protobuf:"varint,3,opt,name=command,proto3,enum=common.Command" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Request_PlayerData) Reset()         { *m = Request_PlayerData{} }
func (m *Request_PlayerData) String() string { return proto.CompactTextString(m) }
func (*Request_PlayerData) ProtoMessage()    {}
func (*Request_PlayerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d2f3dcd4c58ab80, []int{0, 0}
}

func (m *Request_PlayerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_PlayerData.Unmarshal(m, b)
}
func (m *Request_PlayerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_PlayerData.Marshal(b, m, deterministic)
}
func (m *Request_PlayerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_PlayerData.Merge(m, src)
}
func (m *Request_PlayerData) XXX_Size() int {
	return xxx_messageInfo_Request_PlayerData.Size(m)
}
func (m *Request_PlayerData) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_PlayerData.DiscardUnknown(m)
}

var xxx_messageInfo_Request_PlayerData proto.InternalMessageInfo

func (m *Request_PlayerData) GetAction() Request_PlayerData_Action {
	if m != nil {
		return m.Action
	}
	return Request_PlayerData_COMMAND
}

func (m *Request_PlayerData) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *Request_PlayerData) GetCommand() common.Command {
	if m != nil {
		return m.Command
	}
	return common.Command_UP_UP
}

type Response struct {
	Type                 Response_Type `protobuf:"varint,1,opt,name=type,proto3,enum=player.Response_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d2f3dcd4c58ab80, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetType() Response_Type {
	if m != nil {
		return m.Type
	}
	return Response_PING
}

func init() {
	proto.RegisterEnum("player.Request_Type", Request_Type_name, Request_Type_value)
	proto.RegisterEnum("player.Request_PlayerData_Action", Request_PlayerData_Action_name, Request_PlayerData_Action_value)
	proto.RegisterEnum("player.Response_Type", Response_Type_name, Response_Type_value)
	proto.RegisterType((*Request)(nil), "player.Request")
	proto.RegisterType((*Request_PlayerData)(nil), "player.Request.PlayerData")
	proto.RegisterType((*Response)(nil), "player.Response")
}

func init() { proto.RegisterFile("player/services.proto", fileDescriptor_2d2f3dcd4c58ab80) }

var fileDescriptor_2d2f3dcd4c58ab80 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x6a, 0xfa, 0x40,
	0x10, 0xc6, 0x5d, 0xff, 0x21, 0x91, 0x11, 0xfe, 0x86, 0xa1, 0x82, 0x84, 0x1e, 0x6c, 0x4e, 0xf1,
	0xd0, 0x8d, 0x58, 0x7a, 0xa8, 0x37, 0xd1, 0x22, 0x85, 0x6a, 0x65, 0xe9, 0xa5, 0xc7, 0x35, 0x2e,
	0x1a, 0x6a, 0xb2, 0x69, 0x76, 0x2d, 0xf5, 0x61, 0xfa, 0x08, 0x7d, 0xc7, 0x62, 0x36, 0x56, 0x1b,
	0xe8, 0x6d, 0x99, 0xef, 0x9b, 0xdf, 0xec, 0x37, 0x03, 0xed, 0x6c, 0xcb, 0xf7, 0x22, 0x0f, 0x95,
	0xc8, 0xdf, 0xe3, 0x48, 0x28, 0x9a, 0xe5, 0x52, 0x4b, 0xb4, 0x4d, 0xd9, 0xbb, 0x5d, 0xc7, 0x7a,
	0xb3, 0x5b, 0xd2, 0x48, 0x26, 0x61, 0x1e, 0x47, 0x1b, 0x9e, 0xaf, 0xb6, 0x3a, 0x4c, 0xb8, 0xce,
	0xe3, 0x8f, 0x50, 0xad, 0x5e, 0xaf, 0xd7, 0x32, 0x8c, 0x64, 0x92, 0xc8, 0x34, 0xd4, 0xfb, 0xec,
	0xd8, 0xee, 0x7f, 0xd5, 0xc1, 0x61, 0xe2, 0x6d, 0x27, 0x94, 0xc6, 0x00, 0xac, 0x83, 0xd4, 0x21,
	0x5d, 0x12, 0xfc, 0x1f, 0x5c, 0x50, 0x43, 0xa6, 0xa5, 0x4c, 0x9f, 0xf7, 0x99, 0x60, 0x85, 0x03,
	0x87, 0x00, 0x46, 0x9c, 0x70, 0xcd, 0x3b, 0xf5, 0x2e, 0x09, 0x9a, 0x03, 0xaf, 0xea, 0x5f, 0xfc,
	0x38, 0xd8, 0x99, 0xdb, 0xfb, 0x24, 0x00, 0x27, 0x09, 0xef, 0xc0, 0xe6, 0x91, 0x8e, 0x65, 0x5a,
	0x8e, 0xbd, 0xfa, 0x1b, 0x43, 0x47, 0x85, 0x91, 0x95, 0x0d, 0x88, 0x60, 0xa9, 0xad, 0xd4, 0xc5,
	0x7c, 0x8b, 0x15, 0x6f, 0xec, 0x81, 0x73, 0x48, 0xc9, 0xd3, 0x55, 0xe7, 0x5f, 0xc1, 0x6b, 0x51,
	0x93, 0x9a, 0x8e, 0x4d, 0x99, 0x1d, 0x75, 0xbf, 0x0d, 0xb6, 0x01, 0x62, 0x13, 0x9c, 0xf1, 0xd3,
	0x6c, 0x36, 0x9a, 0x4f, 0xdc, 0x9a, 0x7f, 0x09, 0xd6, 0x21, 0x29, 0x36, 0xc0, 0x5a, 0x3c, 0xcc,
	0xa7, 0x6e, 0x0d, 0x01, 0xec, 0xc5, 0xe3, 0xe8, 0xe5, 0x9e, 0xb9, 0xc4, 0x9f, 0x42, 0x83, 0x09,
	0x95, 0xc9, 0x54, 0x09, 0xec, 0xfd, 0xda, 0x57, 0xfb, 0xf4, 0x71, 0xa3, 0x9f, 0x2d, 0xcc, 0x77,
	0xab, 0xd0, 0xc1, 0x10, 0x6c, 0x93, 0x0c, 0xfb, 0xe0, 0x8c, 0x65, 0x9a, 0x8a, 0x48, 0x63, 0xab,
	0x12, 0xde, 0x73, 0xab, 0xd0, 0x80, 0xf4, 0xc9, 0xd2, 0x2e, 0x6e, 0x77, 0xf3, 0x1d, 0x00, 0x00,
	0xff, 0xff, 0xc5, 0xe6, 0xed, 0x88, 0x13, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PlayerClient is the client API for Player service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlayerClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (Player_ConnectClient, error)
}

type playerClient struct {
	cc *grpc.ClientConn
}

func NewPlayerClient(cc *grpc.ClientConn) PlayerClient {
	return &playerClient{cc}
}

func (c *playerClient) Connect(ctx context.Context, opts ...grpc.CallOption) (Player_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Player_serviceDesc.Streams[0], "/player.Player/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &playerConnectClient{stream}
	return x, nil
}

type Player_ConnectClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type playerConnectClient struct {
	grpc.ClientStream
}

func (x *playerConnectClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *playerConnectClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PlayerServer is the server API for Player service.
type PlayerServer interface {
	Connect(Player_ConnectServer) error
}

func RegisterPlayerServer(s *grpc.Server, srv PlayerServer) {
	s.RegisterService(&_Player_serviceDesc, srv)
}

func _Player_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PlayerServer).Connect(&playerConnectServer{stream})
}

type Player_ConnectServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type playerConnectServer struct {
	grpc.ServerStream
}

func (x *playerConnectServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *playerConnectServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Player_serviceDesc = grpc.ServiceDesc{
	ServiceName: "player.Player",
	HandlerType: (*PlayerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Player_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "player/services.proto",
}
