// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: player/services.proto

package player

import (
	common "github.com/richardlt/matrix/sdk-go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request_Type int32

const (
	Request_PING   Request_Type = 0
	Request_PLAYER Request_Type = 1
)

// Enum value maps for Request_Type.
var (
	Request_Type_name = map[int32]string{
		0: "PING",
		1: "PLAYER",
	}
	Request_Type_value = map[string]int32{
		"PING":   0,
		"PLAYER": 1,
	}
)

func (x Request_Type) Enum() *Request_Type {
	p := new(Request_Type)
	*p = x
	return p
}

func (x Request_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Request_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_player_services_proto_enumTypes[0].Descriptor()
}

func (Request_Type) Type() protoreflect.EnumType {
	return &file_player_services_proto_enumTypes[0]
}

func (x Request_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Request_Type.Descriptor instead.
func (Request_Type) EnumDescriptor() ([]byte, []int) {
	return file_player_services_proto_rawDescGZIP(), []int{0, 0}
}

type Request_PlayerData_Action int32

const (
	Request_PlayerData_COMMAND Request_PlayerData_Action = 0
)

// Enum value maps for Request_PlayerData_Action.
var (
	Request_PlayerData_Action_name = map[int32]string{
		0: "COMMAND",
	}
	Request_PlayerData_Action_value = map[string]int32{
		"COMMAND": 0,
	}
)

func (x Request_PlayerData_Action) Enum() *Request_PlayerData_Action {
	p := new(Request_PlayerData_Action)
	*p = x
	return p
}

func (x Request_PlayerData_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Request_PlayerData_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_player_services_proto_enumTypes[1].Descriptor()
}

func (Request_PlayerData_Action) Type() protoreflect.EnumType {
	return &file_player_services_proto_enumTypes[1]
}

func (x Request_PlayerData_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Request_PlayerData_Action.Descriptor instead.
func (Request_PlayerData_Action) EnumDescriptor() ([]byte, []int) {
	return file_player_services_proto_rawDescGZIP(), []int{0, 0, 0}
}

type Response_Type int32

const (
	Response_PING Response_Type = 0
)

// Enum value maps for Response_Type.
var (
	Response_Type_name = map[int32]string{
		0: "PING",
	}
	Response_Type_value = map[string]int32{
		"PING": 0,
	}
)

func (x Response_Type) Enum() *Response_Type {
	p := new(Response_Type)
	*p = x
	return p
}

func (x Response_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Response_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_player_services_proto_enumTypes[2].Descriptor()
}

func (Response_Type) Type() protoreflect.EnumType {
	return &file_player_services_proto_enumTypes[2]
}

func (x Response_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Response_Type.Descriptor instead.
func (Response_Type) EnumDescriptor() ([]byte, []int) {
	return file_player_services_proto_rawDescGZIP(), []int{1, 0}
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Request_Type           `protobuf:"varint,1,opt,name=type,proto3,enum=player.Request_Type" json:"type,omitempty"`
	PlayerData    *Request_PlayerData    `protobuf:"bytes,2,opt,name=playerData,proto3" json:"playerData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_player_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_player_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_player_services_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetType() Request_Type {
	if x != nil {
		return x.Type
	}
	return Request_PING
}

func (x *Request) GetPlayerData() *Request_PlayerData {
	if x != nil {
		return x.PlayerData
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Response_Type          `protobuf:"varint,1,opt,name=type,proto3,enum=player.Response_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_player_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_player_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_player_services_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetType() Response_Type {
	if x != nil {
		return x.Type
	}
	return Response_PING
}

type Request_PlayerData struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Action        Request_PlayerData_Action `protobuf:"varint,1,opt,name=action,proto3,enum=player.Request_PlayerData_Action" json:"action,omitempty"`
	Slot          uint64                    `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	Command       common.Command            `protobuf:"varint,3,opt,name=command,proto3,enum=common.Command" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request_PlayerData) Reset() {
	*x = Request_PlayerData{}
	mi := &file_player_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_PlayerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_PlayerData) ProtoMessage() {}

func (x *Request_PlayerData) ProtoReflect() protoreflect.Message {
	mi := &file_player_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_PlayerData.ProtoReflect.Descriptor instead.
func (*Request_PlayerData) Descriptor() ([]byte, []int) {
	return file_player_services_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Request_PlayerData) GetAction() Request_PlayerData_Action {
	if x != nil {
		return x.Action
	}
	return Request_PlayerData_COMMAND
}

func (x *Request_PlayerData) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *Request_PlayerData) GetCommand() common.Command {
	if x != nil {
		return x.Command
	}
	return common.Command(0)
}

var File_player_services_proto protoreflect.FileDescriptor

const file_player_services_proto_rawDesc = "" +
	"\n" +
	"\x15player/services.proto\x12\x06player\x1a\x12common/types.proto\"\xad\x02\n" +
	"\aRequest\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.player.Request.TypeR\x04type\x12:\n" +
	"\n" +
	"playerData\x18\x02 \x01(\v2\x1a.player.Request.PlayerDataR\n" +
	"playerData\x1a\x9d\x01\n" +
	"\n" +
	"PlayerData\x129\n" +
	"\x06action\x18\x01 \x01(\x0e2!.player.Request.PlayerData.ActionR\x06action\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\x04R\x04slot\x12)\n" +
	"\acommand\x18\x03 \x01(\x0e2\x0f.common.CommandR\acommand\"\x15\n" +
	"\x06Action\x12\v\n" +
	"\aCOMMAND\x10\x00\"\x1c\n" +
	"\x04Type\x12\b\n" +
	"\x04PING\x10\x00\x12\n" +
	"\n" +
	"\x06PLAYER\x10\x01\"G\n" +
	"\bResponse\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.player.Response.TypeR\x04type\"\x10\n" +
	"\x04Type\x12\b\n" +
	"\x04PING\x10\x002:\n" +
	"\x06Player\x120\n" +
	"\aConnect\x12\x0f.player.Request\x1a\x10.player.Response(\x010\x01B2Z0github.com/richardlt/matrix/sdk-go/player;playerb\x06proto3"

var (
	file_player_services_proto_rawDescOnce sync.Once
	file_player_services_proto_rawDescData []byte
)

func file_player_services_proto_rawDescGZIP() []byte {
	file_player_services_proto_rawDescOnce.Do(func() {
		file_player_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_player_services_proto_rawDesc), len(file_player_services_proto_rawDesc)))
	})
	return file_player_services_proto_rawDescData
}

var file_player_services_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_player_services_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_player_services_proto_goTypes = []any{
	(Request_Type)(0),              // 0: player.Request.Type
	(Request_PlayerData_Action)(0), // 1: player.Request.PlayerData.Action
	(Response_Type)(0),             // 2: player.Response.Type
	(*Request)(nil),                // 3: player.Request
	(*Response)(nil),               // 4: player.Response
	(*Request_PlayerData)(nil),     // 5: player.Request.PlayerData
	(common.Command)(0),            // 6: common.Command
}
var file_player_services_proto_depIdxs = []int32{
	0, // 0: player.Request.type:type_name -> player.Request.Type
	5, // 1: player.Request.playerData:type_name -> player.Request.PlayerData
	2, // 2: player.Response.type:type_name -> player.Response.Type
	1, // 3: player.Request.PlayerData.action:type_name -> player.Request.PlayerData.Action
	6, // 4: player.Request.PlayerData.command:type_name -> common.Command
	3, // 5: player.Player.Connect:input_type -> player.Request
	4, // 6: player.Player.Connect:output_type -> player.Response
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_player_services_proto_init() }
func file_player_services_proto_init() {
	if File_player_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_player_services_proto_rawDesc), len(file_player_services_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_player_services_proto_goTypes,
		DependencyIndexes: file_player_services_proto_depIdxs,
		EnumInfos:         file_player_services_proto_enumTypes,
		MessageInfos:      file_player_services_proto_msgTypes,
	}.Build()
	File_player_services_proto = out.File
	file_player_services_proto_goTypes = nil
	file_player_services_proto_depIdxs = nil
}
