name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - run: make test-with-report
      - uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: 'report.xml'
          fail_on_failure: true